const DATA_SUPPLEMENT = [
  // ========== C语言补充 (~8条) ==========
  {
    id: "c-lang", name: "C语言基础", icon: "📘",
    questions: [
      { id: "c-26", tags: ["高频","基础"], q: "指针函数和函数指针的区别？", a: `<p><strong>指针函数</strong>是<strong>返回指针的函数</strong>：<code>int *func(int a);</code>——func是一个函数，返回int*。</p><p><strong>函数指针</strong>是<strong>指向函数的指针</strong>：<code>int (*ptr)(int a);</code>——ptr是一个指针，指向返回int、参数为int的函数。</p><p><strong>区别：</strong>本质完全不同——一个返回指针的函数 vs 一个指向函数的指针。看变量名先和谁结合：先和()结合→函数；先和*结合→指针。</p><pre><code class="language-c">int *get_addr(int id) { return &arr[id]; }  // 指针函数
int (*cmp)(int, int) = &compare;           // 函数指针（回调/排序比较函数）</code></pre>` },
      { id: "c-27", tags: ["进阶","位运算"], q: "嵌入式位运算常用操作和宏定义？", a: `<pre><code class="language-c">#define SET_BIT(reg, bit)    ((reg) |= (1UL << (bit)))    // 置1
#define CLEAR_BIT(reg, bit)  ((reg) &= ~(1UL << (bit)))   // 清0
#define TOGGLE_BIT(reg, bit) ((reg) ^= (1UL << (bit)))    // 翻转
#define READ_BIT(reg, bit)   (((reg) >> (bit)) & 1U)      // 读取</code></pre><p><strong>面试常考：</strong>判断奇偶<code>n & 1</code>；清零最低位1：<code>n & (n-1)</code>（可用于统计二进制1的个数）；交换两数：<code>a^=b; b^=a; a^=b;</code>（异或交换，不用临时变量）。在MCU寄存器操作中，位运算是核心技能。</p>` },
      { id: "c-28", tags: ["进阶"], q: "volatile能保证原子性吗？为什么多任务下还需要锁？", a: `<p><strong>volatile不能保证原子性。</strong>volatile仅告诉编译器"每次从内存读取，不要用寄存器缓存"，但不做任何互斥保护。</p><p>举例：两个任务同时执行<code>counter++</code>（读-改-写三步）。volatile只能保证每个任务读时从内存取最新值，但不能阻止两个任务读到相同值→各加1→各写回→最终只加了1次而非2次。这个问题volatile无法解决。</p><p><strong>解决方案：</strong>多任务并发写必须用临界区或互斥锁保护。单写多读场景（如ISR写标志位+主循环轮询）volatile才够用。volatile解决的是<strong>编译器优化</strong>问题，锁解决的是<strong>并发竞争</strong>问题，两者是不同层面的保护。</p>` },
      { id: "c-29", tags: ["进阶"], q: "结构体成员如何排列可以减少padding？举例说明", a: `<p><strong>原则：</strong>把占用空间大的成员放前面、小的放后面，减少内部填充。</p><pre><code class="language-c">// 差：24字节（char后7字节padding + int在中间）
struct Bad  { char a; double b; int c; };
// 好：16字节（double占8+int占4+char占1+尾1字节padding）
struct Good { double b; int c; char a; };</code></pre><p>也按"对齐要求从大到小"排序。在通信协议帧中如果必须按协议顺序排列，则需要用<code>#pragma pack(1)</code>或<code>__attribute__((packed))</code>紧凑排列。注意pack后可能产生非对齐访问，部分架构（如Cortex-M0）不支持。</p>` },
      { id: "c-30", tags: ["基础","高频"], q: "空指针和野指针的区别？分别会产生什么问题？", a: `<p><strong>空指针(NULL)</strong>：明确指向地址0的指针，表示"不指向任何有效对象"。解引用空指针在大多数系统上会立即触发段错误(Segfault/HardFault)，<strong>容易定位</strong>。</p><p><strong>野指针</strong>：指向"不可预知"内存区域的指针（未初始化、已释放但未置NULL、返回局部变量地址）。解引用野指针后果<strong>不可预知</strong>——可能是段错误、可能读到随机数据、可能破坏其他数据——<strong>极难排查</strong>，因为崩溃点往往与问题根源位置不同。</p><p><strong>面试表述：</strong>"空指针是明确无效、容易发现；野指针是不确定指向、可能悄悄作恶。"防范：初始化指针为NULL、free后立即置NULL、不返回局部变量地址。</p>` },
      { id: "c-31", tags: ["高频","基础"], q: "CPU、MCU、MPU三者有什么区别？", a: `<table><tr><th>类型</th><th>全称</th><th>特点</th></tr><tr><td>CPU</td><td>Central Processing Unit</td><td>中央处理器核心，一般指单个处理器核</td></tr><tr><td>MCU</td><td>Microcontroller Unit</td><td>微控制器——CPU+Flash+RAM+外设(GPIO/UART/SPI等)集成在单芯片上，低功耗低成本，面向嵌入式控制</td></tr><tr><td>MPU</td><td>Microprocessor Unit</td><td>微处理器——仅CPU核心，需外部DRAM/Flash/外设芯片，性能高成本高，面向复杂计算（如运行Linux）</td></tr></table><p>嵌入式面试中常被问到的区分：MCU跑RTOS（FreeRTOS/RT-Thread），MPU跑Linux/QNX。汽车中MCU做实时控制，MPU做ADAS/座舱计算。</p>` },
      { id: "c-32", tags: ["进阶"], q: "宏函数和函数的区别？宏有哪些常见陷阱？", a: `<p><strong>宏陷阱一：参数多次求值。</strong><code>#define MAX(a,b) ((a)>(b)?(a):(b))</code>；调用<code>MAX(i++, j++)</code>会因参数被多次求值导致i或j被错误地递增两次。</p><p><strong>宏陷阱二：缺少括号导致优先级错误。</strong><code>#define SQUARE(x) x*x</code>；<code>SQUARE(1+2)</code>展开为<code>1+2*1+2=5</code>而非<code>9</code>。应改为<code>((x)*(x))</code>。</p><p><strong>宏陷阱三：多语句宏不安全。</strong><code>#define SWAP(a,b) {int t=a;a=b;b=t;}</code>在if-else中展开会语法错误。应用<code>do{...}while(0)</code>包裹。</p><p><strong>建议：</strong>在C99+环境中优先用<code>static inline</code>函数替代宏函数——有类型检查、无副作用、可调试。</p>` }
    ]
  },
  // ========== Linux常用命令补充 (~10条) ==========
  {
    id: "linux", name: "Linux嵌入式开发", icon: "🐧",
    questions: [
      { id: "lx-16", tags: ["Linux","命令","高频"], q: "top命令的用法？与ps的区别？", a: `<p><strong>top</strong>是实时动态进程监控工具，默认3秒刷新。常用交互键：<code>M</code>(按内存排序)、<code>P</code>(按CPU排序)、<code>1</code>(显示所有CPU核心)、<code>k</code>(杀死进程)、<code>u</code>(按用户过滤)、<code>q</code>(退出)。<code>top -H</code>显示线程级资源占用。<code>top -o %MEM</code>直接按内存降序。</p><p><strong>与ps的区别：</strong>top是动态实时刷新（类似任务管理器），ps是静态快照（执行瞬间的进程列表）。查看系统负载趋势用top，脚本中获取进程信息用ps。</p>` },
      { id: "lx-17", tags: ["Linux","命令","高频"], q: "ps命令的常用组合？ps aux和ps -ef的区别？", a: `<table><tr><th>命令</th><th>风格</th><th>用途</th></tr><tr><td>ps aux</td><td>BSD风格</td><td>显示所有用户进程详情(CPU%/MEM%/VSZ/RSS)，适合资源监控</td></tr><tr><td>ps -ef</td><td>UNIX标准</td><td>显示完整格式(PPID/STIME)，适合分析进程父子关系</td></tr></table><p>实用组合：<code>ps -eLf</code>查看线程（多了LWP线程ID列）；<code>ps aux | grep xxx</code>过滤特定进程；<code>ps -T -p &lt;PID&gt;</code>查看指定进程的所有线程。</p>` },
      { id: "lx-18", tags: ["Linux","命令"], q: "kill命令常用信号？SIGTERM和SIGKILL的区别？", a: `<table><tr><th>信号</th><th>编号</th><th>特点</th></tr><tr><td>SIGTERM</td><td>15</td><td>默认，允许进程优雅退出（保存状态/关闭文件/释放资源），进程可捕获处理</td></tr><tr><td>SIGKILL</td><td>9</td><td>强制终止，进程不可捕获/忽略，由内核直接杀死，可能资源未释放/数据丢失</td></tr><tr><td>SIGINT</td><td>2</td><td>Ctrl+C中断，可捕获</td></tr><tr><td>SIGSTOP</td><td>19</td><td>暂停进程，不可捕获</td></tr></table><p><strong>最佳实践：</strong>先<code>kill &lt;PID&gt;</code>（-15）给进程清理机会，无响应再用<code>kill -9 &lt;PID&gt;</code>。<code>killall 进程名</code>按名称批量终止。</p>` },
      { id: "lx-19", tags: ["Linux","命令"], q: "free命令如何查看内存？buff/cache高是怎么回事？", a: `<p><code>free -h</code>（人类可读格式）或<code>free -m</code>（MB单位）查看内存。</p><p><strong>关键字段：</strong>total（总物理内存）、used（已使用）、free（完全空闲）、<strong>buff/cache</strong>（缓冲区和页面缓存，Linux主动利用空闲内存做文件系统缓存）、<strong>available</strong>（实际可用=free+可回收的buff/cache）。</p><p><strong>buff/cache高不代表内存不够</strong>——这是Linux的正常行为，缓存随时可被回收给应用使用。真正需要关注的是available是否接近0。如果available持续很低，才说明内存不足。嵌入式设备上需关注是否有内存泄漏导致available持续下降。</p>` },
      { id: "lx-20", tags: ["Linux","命令"], q: "df和du的区别？如何排查磁盘空间问题？", a: `<p><code>df -h</code>查看文件系统级别的磁盘使用（分区挂载点）；<code>du -sh /path</code>统计目录/文件级别的占用。</p><p><strong>区别：</strong>df从文件系统元数据获取，du遍历文件累计。两者不一致通常是"已删除但仍被进程持有的文件"（文件删了但fd未关闭，空间未释放）导致。</p><p><strong>排查：</strong><code>df -i</code>查看inode使用情况（小文件过多可能inode耗尽但空间还有）。查找大文件：<code>du -sh /* | sort -rh | head -10</code>。找到已删除但占用空间的文件：<code>lsof | grep deleted</code>。</p>` },
      { id: "lx-21", tags: ["Linux","命令","高频"], q: "dmesg命令的作用？能排查哪些问题？", a: `<p><code>dmesg</code>查看内核环形缓冲区日志，记录驱动加载、硬件检测、OOM Killer、内核错误等信息。</p><p><strong>典型用途：</strong></p><ul><li><strong>硬件检测</strong>：<code>dmesg | grep -i usb</code>查看USB设备枚举情况</li><li><strong>驱动加载</strong>：<code>dmesg | grep -i driver</code>检查驱动probe是否成功</li><li><strong>OOM排查</strong>：<code>dmesg | grep -i "out of memory"</code>查找被OOM Killer杀掉的进程</li><li><strong>内核崩溃</strong>：查看kernel panic/oops栈回溯信息</li><li><strong>磁盘错误</strong>：<code>dmesg | grep -i "ata\|sd\|error"</code>查看SATA/SCSI控制器错误</li></ul><p>嵌入式开发中，串口终端启动时打印的内核信息本质上就是dmesg内容。</p>` },
      { id: "lx-22", tags: ["Linux","进阶"], q: "Linux进程有哪几种状态？各用什么符号表示？", a: `<table><tr><th>状态</th><th>符号</th><th>说明</th></tr><tr><td>运行态(Running)</td><td>R</td><td>正在执行(当前进程)或在就绪队列等待调度</td></tr><tr><td>可中断睡眠</td><td>S</td><td>等待事件(如I/O完成/信号量)，可被信号唤醒。大部分进程处于此状态</td></tr><tr><td>不可中断睡眠</td><td>D</td><td>等待硬件I/O，不响应任何信号（连SIGKILL也不行）。通常极短暂，若进程长时间处于D→可能磁盘/存储故障</td></tr><tr><td>停止态(Stopped)</td><td>T</td><td>被Ctrl+Z暂停或被调试器(gdb)停止，需SIGCONT恢复</td></tr><tr><td>僵尸态(Zombie)</td><td>Z</td><td>进程已退出但父进程未调用wait()回收资源。大量僵尸→父进程Bug，需修复父进程</td></tr></table><p><code>top</code>或<code>ps aux</code>的STAT列显示进程当前状态。</p>` },
      { id: "lx-23", tags: ["Linux","进阶","高频"], q: "自旋锁(spinlock)、互斥锁(mutex)、信号量(semaphore)的对比？", a: `<table><tr><th>特性</th><th>自旋锁</th><th>互斥锁</th><th>信号量</th></tr><tr><td>等待方式</td><td>忙等待(CPU空转)</td><td>睡眠阻塞</td><td>睡眠阻塞</td></tr><tr><td>并发度</td><td>一次一个</td><td>一次一个</td><td>可允许多个(计数)</td></tr><tr><td>释放者</td><td>必须是获取者</td><td>必须是获取者</td><td>可不同于获取者</td></tr><tr><td>中断上下文</td><td>可用</td><td>不可用</td><td>不可用</td></tr><tr><td>适用场景</td><td>极短临界区(μs级)、SMP多核</td><td>较长临界区、进程上下文</td><td>资源池管理、同步</td></tr></table><p><strong>选择口诀：</strong>中断上下文只能用spinlock；进程上下文+极短临界区→spinlock；进程上下文+可睡眠→mutex；管理多个同类型资源→semaphore。持spinlock期间绝对不可睡眠/调度。</p>` },
      { id: "lx-24", tags: ["Linux","进阶"], q: "硬中断和软中断的区别？Linux中断为什么分上下半部？", a: `<p><strong>硬中断</strong>：由硬件设备触发（如网卡收到包→产生中断），每个硬件有独立IRQ号，由硬件中断控制器(NVIC/GIC)传递给CPU。ISR在关中断或高优先级上下文中执行，必须极短。</p><p><strong>软中断</strong>：由软件触发（如tasklet/softirq），用于处理硬中断中不方便执行的耗时操作（如网络协议栈处理）。运行在中断上下文但可被硬中断打断。优先级低于硬中断。</p><p><strong>上下半部分离的原因：</strong>硬中断需要快速响应（上半部只做"清中断+拷贝关键数据+标记下半部"）。下半部（tasklet/workqueue/threaded IRQ）处理数据解析、网络协议栈等耗时操作，此时中断已重新使能，不影响系统响应。</p><p>一句话：上半部抢时间，下半部做事情。</p>` }
    ]
  },
  // ========== 大厂面试真题扩充 (~15条) ==========
  {
    id: "interviews", name: "大厂面试真题", icon: "🏢",
    questions: [
      { id: "iv-21", tags: ["高频","TCP/IP"], q: "TCP三次握手详细过程？为什么不是两次或四次？", a: `<p><strong>三次握手：</strong>CLIENT→SYN(seq=x)→SERVER→SYN+ACK(seq=y, ack=x+1)→CLIENT→ACK(ack=y+1)→连接建立。</p><p><strong>为什么不是两次？</strong>两次握手无法防止已失效的连接请求到达服务端。如果客户端第一个SYN因网络延迟很久才到→服务端回复SYN+ACK并认为连接已建立→但客户端早已放弃此连接→服务端一直等待客户端发数据→浪费资源。引入第三次握手：客户端不确认则连接不建立。</p><p><strong>为什么不是四次？</strong>服务端的SYN和ACK可以合并在一个报文中发送（SYN+ACK作为一个包），不需要分开。没有额外信息需要传递。</p>` },
      { id: "iv-22", tags: ["ARM","高频"], q: "MMU是硬件还是软件？虚拟地址到物理地址的映射过程？", a: `<p><strong>MMU(Memory Management Unit)是CPU内部的硬件模块</strong>，通常集成在Cortex-A系列及以上的处理器中。它负责地址翻译和内存访问权限检查。</p><p><strong>映射过程：</strong>CPU发出虚拟地址→MMU查TLB(Translation Lookaside Buffer，页表缓存)→TLB命中则直接获得物理地址→TLB未命中则查内存中的多级页表(PGD→PMD→PTE)→获取物理地址后填入TLB→返回物理地址完成访存。</p><p><strong>为什么需要MMU？</strong></p><ul><li>进程隔离（每个进程看到的地址空间相同但映射到不同物理页）</li><li>内存保护（只读/不可执行等权限）</li><li>按需换页（虚拟内存可大于物理内存）</li></ul><p>Cortex-M系列没有MMU只有MPU（不翻译地址仅做保护），只能跑RTOS不能跑完整Linux。</p>` },
      { id: "iv-23", tags: ["高频","调试"], q: "堆溢出和栈溢出分别由什么引起？怎么排查？", a: `<p><strong>栈溢出（Stack Overflow）：</strong>局部变量过大（函数内定义大数组）、递归深度过深、函数嵌套调用层数过多。在RTOS中任务栈分配太小也会溢出。</p><p><strong>堆溢出（Heap Overflow）：</strong>内存泄漏（malloc后忘记free→堆空间耗尽）、内存碎片（虽然有总空间但无连续块）、写越界（破坏了堆管理结构的元数据）。</p><p><strong>排查方法：</strong></p><ul><li>栈溢出：查看栈哨兵字节是否被覆盖、HardFault寄存器(CFSR)显示IMPRECISERR或MemManage fault、用uxTaskGetStackHighWaterMark()监控剩余栈</li><li>堆溢出：观察剩余堆空间趋势（持续下降→泄漏）、Valgrind检测、在可疑分配/释放加日志统计</li></ul>` },
      { id: "iv-24", tags: ["FreeRTOS","高频"], q: "FreeRTOS为什么用队列传递数据而不是全局变量？", a: `<p><strong>三个核心原因：</strong></p><ol><li><strong>线程安全</strong>：队列内置了临界区保护（关中断+环形缓冲区），多任务同时读写队列不会出现竞态条件。全局变量需要手动加锁——忘了就Bug。</li><li><strong>阻塞等待</strong>：队列支持阻塞超时（消费者可等待数据到达才唤醒），省去了轮询开销。全局变量只能轮询或外加信号量。</li><li><strong>数据缓冲</strong>：队列有多条数据缓冲能力（队列深度），生产者消费者速度差异被队列吸收。全局变量只能保留最新值——数据会丢失。</li></ol><p><strong>但队列有开销</strong>——创建RAM占用、每次数据拷贝。如果仅需简单标志位（如"任务是否停止"），全局变量+volatile也可以。选型取决于是否需要缓冲、是否需要阻塞、是否需要并发保护。</p>` },
      { id: "iv-25", tags: ["ARM","高频"], q: "Cache一致性问题是什么？什么时候会出现？如何解决？", a: `<p><strong>Cache一致性(Cache Coherency)问题：</strong>多核系统中，核A修改共享变量→仅更新了核A的L1 Cache→核B的L1 Cache仍持有旧副本→核B读到过期数据。</p><p><strong>出现场景：</strong></p><ul><li>多核间通过共享内存通信</li><li>DMA与CPU访问同一块内存（DMA写内存→CPU Cache可能有旧数据）</li></ul><p><strong>解决方案：</strong></p><ul><li><strong>硬件方案</strong>：MESI协议（Modified/Exclusive/Shared/Invalid），通过总线嗅探自动维护一致性。Cortex-A的CCI-400缓存一致性互联</li><li><strong>软件方案</strong>：DMA操作前Cache Clean（写回脏数据到内存）→DMA完成后Cache Invalidate（使无效缓存行，下次从内存读）；共享变量标记为Non-Cacheable内存（通过MMU/MPU配置）</li><li><strong>屏障指令</strong>：DMB/DSB/ISB保证访存顺序</li></ul>` },
      { id: "iv-26", tags: ["高频","面试技巧"], q: "如果程序在客户现场出现偶发性崩溃，你会怎么排查？", a: `<ol><li><strong>现场信息收集</strong>：串口日志/核心转储(coredump)/Crash Dump闪存记录/故障指示灯/复位原因寄存器(RCC_CSR)</li><li><strong>能否复现</strong>：能→实验室复现+二分法缩小变量范围；不能→仅从现场数据逆向分析</li><li><strong>硬件排查</strong>：测电源纹波(示波器看有无跌落)、复位引脚波形、时钟输出、看门狗触发时间线</li><li><strong>软件分析</strong>：HardFault寄存器(CFSR/HFSR/MMFAR/BFAR)→判断异常类型：IMPRECISERR(可能栈溢出/非对齐)、MemManage(MPU违规)、BusFault(非对齐/非法地址)</li><li><strong>根因修复</strong>：定位后修复+加监控(Assert/栈哨兵/独立看门狗/异常上下文保存到Flash)</li></ol><p>面试关键：展示系统性排查思维，而非跳到最后结论。展示从现象→"缩小范围"→"分析根因"的逻辑链。</p>` },
      { id: "iv-27", tags: ["高频","ARM"], q: "Linux内核访问的是虚拟地址还是物理地址？", a: `<p><strong>Linux内核使用虚拟地址</strong>——在ARM32上内核空间映射在3GB~4GB虚拟地址范围。内核启动时建立页表，将内核代码/数据的物理地址映射到这段虚拟地址空间。</p><p><strong>有一个重要例外：</strong>内核启动早期（start_kernel之前）MMU未开启时使用的是物理地址。访问硬件寄存器时先通过ioremap将物理地址映射到内核虚拟地址空间再去访问，不能直接操作物理地址。</p><p><strong>为什么内核也用虚拟地址？</strong>统一的内存管理模型（伙伴系统/slab/kmalloc都在虚拟地址空间管理）、方便与用户态的copy_from_user/copy_to_user交互（同一页表体系）。</p><p><strong>一句话：</strong>有MMU的系统上，一切访存都经过MMU翻译（包括内核），物理地址仅存在于页表条目和DMA等特殊场景。</p>` },
      { id: "iv-28", tags: ["高频","I2C","SPI"], q: "I2C总线为什么需要上拉电阻？SPI不需要？", a: `<p><strong>I2C的SDA和SCL都是开漏(Open-Drain)输出</strong>——只能输出低电平或高阻态，不能主动输出高电平。必须通过外部上拉电阻（通常4.7kΩ）将总线拉到高电平。开漏设计的优势：支持多主仲裁（多个设备同时输出低不会短路）、支持时钟拉伸（从设备拉低SCL让主设备等待）。</p><p><strong>SPI是推挽输出</strong>——MOSI和SCLK可以主动输出高/低电平，不需要外部上拉电阻。SPI没有多主仲裁（主设备主动选片CS）、没有应答机制，推挽驱动速度更快。</p><p><strong>本质原因：</strong>I2C的开漏机制支持多设备挂同一总线做线与逻辑和仲裁；SPI是点对多点主从模式，主设备独占控制时序，推挽设计提高速率。两者设计理念完全不同。</p>` },
      { id: "iv-29", tags: ["高频","TCP/IP"], q: "Socket通信的基本流程？TCP和UDP分别怎么用？", a: `<p><strong>TCP Socket（面向连接）：</strong>Server: socket()→bind()→listen()→accept()(阻塞等待)→recv()/send()→close()。Client: socket()→connect()→send()/recv()→close()。</p><p><strong>UDP Socket（无连接）：</strong>Server: socket()→bind()→recvfrom()→sendto()→close()。Client: socket()→sendto()→recvfrom()→close()。不需要connect/listen/accept。</p><p><strong>关键区别：</strong>TCP需要三次握手建立连接后才通信，recv/send是有序可靠的字节流；UDP直接发包，recvfrom/sendto每次都要指定对方地址，无顺序/可靠性保证。嵌入式选型：文件传输/固件升级→TCP，实时数据/传感器广播→UDP。</p>` },
      { id: "iv-30", tags: ["高频","C语言"], q: "常见的段错误(Segmentation Fault)原因有哪些？如何调试？", a: `<p><strong>常见原因：</strong></p><ol><li><strong>空指针解引用</strong>：<code>int *p=NULL; *p=5;</code>——最常见</li><li><strong>数组越界</strong>：写入超出数组边界的索引，破坏了栈/堆结构</li><li><strong>野指针</strong>：访问已释放或未初始化的指针</li><li><strong>栈溢出</strong>：递归过深或局部变量过大</li><li><strong>对只读内存的写入</strong>：如写.rodata段的字符串常量</li><li><strong>非对齐访问</strong>：部分架构上未对齐的地址读多字节值</li></ol><p><strong>调试方法：</strong>gdb加载core dump→<code>bt</code>看调用栈→<code>info registers</code>看崩溃时寄存器→<code>frame N</code>切换到对应栈帧→<code>info locals</code>看局部变量。或用<code>valgrind ./app</code>运行检测非法内存访问。嵌入式上分析HardFault寄存器+栈回溯定位。</p>` }
    ]
  },
  // ========== ARM/中断/通信补充 (~5条) ==========
  {
    id: "arm", name: "ARM架构", icon: "🔲",
    questions: [
      { id: "arm-11", tags: ["ARM","高频"], q: "ARM异常向量表中有哪些异常？进入异常时CPU做了什么？", a: `<p>Cortex-M异常向量表前16项(0-15号)是系统异常：Reset、NMI、HardFault、MemManage、BusFault、UsageFault、SVCall、DebugMonitor、PendSV、SysTick。后面是外设中断IRQ0-IRQn。</p><p><strong>进入异常时CPU自动硬件动作（零开销）：</strong></p><ol><li>自动压栈R0,R1,R2,R3,R12,LR,PC,xPSR到当前栈（8×4=32字节）</li><li>从向量表对应位置取异常向量地址→更新PC</li><li>LR设置为EXC_RETURN特殊值（标识返回模式，如0xFFFFFFF9=返回Thread模式用MSP）</li><li>xPSR更新为异常编号</li></ol><p>整个过程全部硬件完成，ISR代码开始时已经有完整保存的上下文。退出时执行BX LR→硬件识别EXC_RETURN→自动出栈恢复寄存器。这是Cortex-M相比Cortex-A在实时性上的核心优势之一。</p>` }
    ]
  },
  {
    id: "protocols", name: "通信协议", icon: "📡",
    questions: [
      { id: "p-26", tags: ["SPI","进阶"], q: "硬件SPI和软件SPI(GPIO模拟)的区别？什么时候用哪个？", a: `<p><strong>硬件SPI：</strong>MCU内置SPI控制器+移位寄存器，CPU只需写入/读取数据寄存器，硬件自动产生SCLK和收发时序。速率高(可达F_CPU/2 即几十MHz)、CPU占用低（尤其配合DMA）、时序精确。占用固定的SPI引脚。</p><p><strong>软件SPI(GPIO Bit-Banging)：</strong>通过GPIO手动控制SCLK/MOSI/MISO/CS的电平变化实现SPI协议。速率低(通常在几百kHz)、CPU持续忙于位操作。优点是引脚灵活（任意GPIO都可）、不占用硬件SPI控制器。</p><p><strong>选型：</strong>有硬件SPI且速率要求高（LCD/Flash）→用硬件SPI+DMA；引脚特殊或硬件SPI不够用时→用软件SPI（低速传感器）。大多数场景优先硬件SPI。</p>` }
    ]
  }
];

const EMBEDDED_DATA = [
  ...DATA_PART1,
  ...DATA_PART1B,
  ...DATA_PART2,
  ...DATA_PART3,
  ...DATA_RESUME,
  ...DATA_SUPPLEMENT
];
