      // ========== 个人项目 - 系统架构设计 ==========
      { id: "ri-15", tags: ["架构","五层架构","高频"], q: "[项目] 整体架构怎么设计的？五层分别做什么？六个线程怎么分工？", a: `<p><strong>五层架构：</strong></p><ol><li><strong>应用层</strong>：创建六个线程（LVGL渲染5ms、传感器轮询50ms、BLE通信20ms、按键扫描20ms、idle电源管理50ms、stop休眠管理100ms）加一个500ms软件定时器做UI数据刷新和空闲计时</li><li><strong>服务层</strong>：全部纯C、零硬件依赖的业务逻辑——心率算法（IIR去直流+七点窗峰值检测）、血氧算法（AC/DC比值法）、电量查表、计算器引擎（中缀转后缀表达式求值）、BLE协议解析、OTA Ymodem状态机。可在PC上独立编译测试</li><li><strong>驱动层</strong>：每外设实现ops函数指针接口——IMU的imu_ops_t、显示的display_ops_t共十一类。MPU6050填一份，ST7789填一份。驱动层只依赖HAL接口头文件，不直接碰寄存器</li><li><strong>系统抽象层</strong>：OSAL封装RT-Thread API + HAL封装外设操作（GPIO/SPI/I2C/ADC/UART/RTC/WDT）。全项目仅此层8个文件含芯片寄存器代码。换芯片只改这一层</li><li><strong>硬件层</strong>：GD32厂商库和CMSIS，不修改</li></ol><p>层间 App→Service→Driver→HAL 全部直接函数调用纳秒级延迟。跨线程才用IPC——按键通知LVGL用消息队列、唤醒通知用邮箱。</p>` },
      { id: "ri-16", tags: ["架构","多态","函数指针","高频"], q: "[项目] ops结构体怎么实现多态？举例子", a: `<p>接口定义一个全是函数指针的结构体：</p><pre><code class="language-c">typedef struct {
    int32_t (*init)(void);
    bool    (*read_accel_gyro)(drv_imu_data_t *);
    bool    (*is_data_ready)(void);
} imu_ops_t;</code></pre><p>MPU6050驱动把这些指针填上寄存器读写函数，生成mpu6050_imu_ops常量。上层只拿到imu_ops_t*指针，调<code>ops->read_accel_gyro(&data)</code>时编译器通过函数指针间接跳转——这就是C语言的多态。上层代码没有一行<code>#include "mpu6050.h"</code>。换芯片只改注册表里的一行ops指针，其余代码零改动。</p>` },
      { id: "ri-17", tags: ["架构","依赖倒置","SOLID","高频"], q: "[项目] 设备注册表是什么？怎么实现依赖倒置？", a: `<p>一个全局数组g_registry[16]，启动时在board_init()把所有外设ops注入：</p><pre><code class="language-c">dev_register("imu",     &mpu6050_imu_ops);
dev_register("display", &st7789_display_ops);</code></pre><p>服务层按名称查找：<code>imu_ops_t *imu = dev_get_ops("imu");</code>，内部是for循环strcmp匹配。</p><p><strong>依赖倒置的含义：</strong>传统写法是服务层<code>#include "mpu6050.h"</code>——上层依赖具体实现，换芯片要改服务层。注册表反转了这个方向——服务层只依赖imu_ops_t抽象接口，具体是谁由board_init注入。依赖从"上层→具体"变成了"上层→抽象←具体"，这就是SOLID依赖倒置在C语言中的落地。</p><p>我最初想引入Linux的platform bus做设备注册/匹配/probe，写完伪代码发现项目只有10个外设且编译期已知，probe/match的代码量远超实际价值。最终60行注册表替代了300+行过度设计。</p>` },
      { id: "ri-18", tags: ["架构","IPC","实时性","高频"], q: "[项目] 层间直接调用和线程间消息队列怎么决策的？走过什么弯路？", a: `<p>最初想层间全用消息队列做彻底解耦。画完时序图发现一次传感器读取需要4次上下文切换——App→Service→Driver→返回路径，累积延迟对LVGL 60fps帧刷新不可接受。查阅PX4飞控和ESP-IDF源码后确认"<strong>垂直直接调用+水平消息队列</strong>"才是嵌入式实时系统的最佳实践。</p><p><strong>最终方案：</strong>同线程调用链(垂直)全部直接函数调用、纳秒级延迟；只有跨线程(水平)才用IPC——按键通知LVGL用消息队列、唤醒通知用邮箱。这纠正了我对"彻底解耦"的执念——解耦有代价（上下文切换），要在性能和可维护性之间找平衡点。</p>` },
      { id: "ri-19", tags: ["架构","高内聚低耦合","高频"], q: "[项目] 高内聚低耦合具体怎么体现？举个例说明", a: `<p><strong>高内聚——每个模块只做一件事：</strong>svc_spo2_algo.c只管PPG信号处理和心率血氧计算，用环形缓冲区管理数据，不碰GPIO和I2C。hal_i2c_stm32.c只管I2C位操作，不关心上层是温湿度传感器还是EEPROM。打开任一文件能看懂全部逻辑。</p><p><strong>低耦合——模块间只通过接口通信：</strong>svc_sensor_fusion.c通过dev_get_ops("imu")获取IMU接口，没有<code>#include "mpu6050.h"</code>。app_ui_pages.c通过svc_data_store_get_sensors()获取数据，不访问全局变量。按键线程os_mb_send(idlebreak_mb)通知idle线程，两个线程互不调用对方函数。</p><p>效果：改HAL不影响Service，加新传感器只需实现ops然后注册，不改已有代码。</p>` },
      { id: "ri-20", tags: ["架构","线程","RT-Thread","高频"], q: "[项目] 线程优先级和时间片怎么分配的？为什么LVGL最高优？", a: `<p><strong>六个线程分四个等级（数字越小优先级越高）：</strong></p><table><tr><th>线程</th><th>优先级</th><th>时间片</th><th>周期</th><th>核心工作</th></tr><tr><td>lvgl</td><td>7</td><td>15ms</td><td>5ms</td><td>lv_timer_handler帧渲染，读触摸坐标，检测触摸唤醒</td></tr><tr><td>idle_mgr</td><td>9</td><td>5ms</td><td>50ms</td><td>等idle_mq（息屏触发）和idlebreak_mb（唤醒触发）</td></tr><tr><td>stop_mgr</td><td>10</td><td>5ms</td><td>100ms</td><td>永久阻塞等stop_mq，收到后关外设进STOP模式</td></tr><tr><td>sensor</td><td>11</td><td>5ms</td><td>50ms</td><td>I2C读传感器，调血氧算法，写svc_data_store</td></tr><tr><td>ble</td><td>12</td><td>5ms</td><td>20ms</td><td>轮询BLE标志，协议解析或Ymodem状态机</td></tr><tr><td>key</td><td>13</td><td>5ms</td><td>20ms</td><td>读GPIO，检测下降沿，发MQ通知LVGL和idle</td></tr></table><p><strong>为什么LVGL最高优？</strong>智能手表和人交互的唯一界面就是屏幕——画面卡顿立刻可感知。LVGL每5ms需要跑一次帧渲染，sensor的I2C忙等（约5-10ms）如果优先级比LVGL高，会挡住渲染导致画面跳帧。LVGL在优先级7意味着不管sensor在做什么——调度器会立刻把CPU抢过来交给LVGL。sensor数据晚20ms更新用户完全感受不到，LVGL晚5ms刷新立刻看到顿一下。这是"用户体验优先于后台数据时效"的原则。</p><p>LVGL时间片15ms而非默认5ms——优先级7上没有同级竞争者，时间片轮转只在同优先级间触发。15ms是防御值——万一将来有同级线程，至少能完整渲染一帧再让出CPU。</p>` },
      { id: "ri-21", tags: ["架构","线程"], q: "[项目] 为什么sensor优先级11？idle为什么是9？", a: `<p><strong>sensor优先级11：</strong>I2C用os_udelay忙等读FIFO——一次约5-10ms。如果sensor优先级高于LVGL，每次I2C期间LVGL的5ms定时到了也无法渲染。sensor降到11后LVGL(7)/idle(9)/stop(10)都可随时抢占它。传感器数据晚几十ms对功能无影响——UI下一次500ms刷新时自然拿到最新值。</p><p><strong>idle优先级9：</strong>高于sensor(11)——保证idle线程就绪时不被sensor的I2C阻塞。最坏情况被LVGL挡住：LVGL正在执行一帧lv_timer_handler，idle需等LVGL主动让出CPU（最多5ms）。5ms的亮度恢复延迟人眼完全感知不到（视觉反应时间约100-200ms）。所以idle不需要和LVGL同级——9就够了。</p><p><strong>sensor基准周期从500ms改为50ms：</strong>用单一uint8_t计数器取模分频——tick%2→IMU每100ms、tick%10→心率血氧每500ms、tick%40→温湿度每2s。单计数器方案比原来三个独立静态计数器的好处是所有传感器基于同一时间基准，不存在各计数器因不同复位周期导致的相位漂移。</p>` },

      // ========== 个人项目 - 健康算法 ==========
      { id: "ri-22", tags: ["算法","心率","PPG","高频"], q: "[项目] 从手指放上传感器到显示心率血氧，完整处理链路是怎样的？", a: `<p><strong>先理解三个概念：</strong></p><ul><li><strong>PPG：</strong>MAX30102的红光和红外LED交替发光照进手指，心脏每跳一次血管血容量增加→光被多吸收一点→反射光减少→传感器数值出现微小下降。这个随心跳波动的光强信号就是光电容积脉搏波</li><li><strong>DC（直流分量）：</strong>皮肤/骨骼/肌肉对光的固定衰减，数值很大（约十万量级），不随脉搏变化</li><li><strong>AC（交流分量）：</strong>随脉搏波动的部分——幅度很小，只有DC的约1/50到1/100。AC才是携带心率和血氧信息的核心</li></ul><p><strong>第一步——硬件自动采样：</strong>MAX30102以100sps自动工作，每周期10ms红光LED亮411μs+红外LED亮411μs采样，各出18位值成对存入32槽FIFO。每500ms驱动轮询一次读出最多8对。</p><p><strong>第二步——一阶IIR去直流：</strong>baseline = baseline + 0.01×(raw - baseline)。α=0.01、截止频率约0.16Hz，刚好低于最低心率0.5Hz。AC = |raw - baseline|。红光和红外各独立做一遍。</p><p><strong>第三步——心率计算：</strong>七点滑动窗口扫描去直流后的红光AC——中心点≥其余六个点认定为心跳峰值。两次峰间隔<425ms的丢弃（>141bpm噪声）。连续收集7个瞬时心率取算术平均。动态阈值=窗口均值+(极差÷4)，自动适应不同用户信号强弱。</p><p><strong>第四步——血氧计算：</strong>两路AC各维护32点滑动窗口。DC=窗口均值，AC=窗口峰峰值。R=(红光AC/红光DC)÷(红外AC/红外DC)——先各自除以DC做归一化（排除手指粗细肤色影响），再相除约掉DC绝对值，R值只反映血红蛋白的化学特性。SpO2=110-25×R，钳位70%~100%。</p>` },
      { id: "ri-23", tags: ["算法","DSP","高频"], q: "[项目] IIR的α为什么取0.01？窗口为什么是七点？±3bpm怎么验证的？", a: `<p><strong>α=0.01</strong>在100sps下截止约0.16Hz——刚好低于0.5Hz最低心率，保留完整脉搏波动。α取0.1则截止1.6Hz→脉搏信号会被当DC吃掉。α取0.001太慢→姿势变化导致基线抬升要几十秒才能跟上，这期间血氧值不准。</p><p><strong>七点窗：</strong>跨70ms，刚好捕获一个心跳收缩峰（宽约100-200ms）的完整上升下降沿。三点太窄易被噪声触发，七点在抗噪和灵敏度间平衡最好。</p><p><strong>验证方法：</strong>Polar H10胸带做对照——五人静坐加步行各三分钟，每整分钟对比手表输出和Polar值，共30组数据。静坐±2bpm，步行±3bpm。运动伪影用MPU6050加速度辅助——三轴合成超1.5g标记数据不可靠不参与计算。</p>` },
      { id: "ri-24", tags: ["算法","血氧"], q: "[项目] 为什么心率只要AC、血氧需要AC和DC两个？区别在哪？", a: `<p><strong>心率看"什么时候跳"</strong>——AC峰值在时间轴上的位置，DC不影响峰出现的时刻。只需AC信号做峰检测即可。</p><p><strong>血氧看"跳的幅度比例"</strong>——不同人的皮肤吸收差异导致AC绝对值差距巨大（皮肤厚的AC可能只有皮肤薄的1/3），直接比绝对值不准确。必须先除以各自的DC做归一化，把AC变成和手指物理条件无关的比例值，再跨通道比较。此时DC被约掉，R值只反映血红蛋白的化学特性。这是PPG血氧计算最核心的原理。</p>` },

      // ========== 个人项目 - OTA升级 ==========
      { id: "ri-25", tags: ["OTA","Bootloader","高频"], q: "[项目] Flash分区怎么划分的？从PC端SecureCRT到手表重启的完整OTA流程？", a: `<p><strong>Flash分区（GD32F405 1MB）：</strong></p><pre><code>0x08000000 ┌──────────────────┐
           │   Bootloader     │  16KB （上电启动）
0x08004000 ├──────────────────┤
           │   APP_A          │  496KB（当前运行固件）
0x08080000 ├──────────────────┤
           │   APP_B          │  496KB（OTA目标分区）
0x080FC000 ├──────────────────┤
           │   Reserved       │  16KB
0x080FFFFF └──────────────────┘</code></pre><p><strong>阶段一——进入OTA：</strong>手表收到OV+OTA命令→EEPROM写UPDATE_STATUS=0x01（传输中）→回复+OTA_READY→每秒发'C'（请求CRC16校验模式的Ymodem传输）。</p><p><strong>阶段二——Ymodem握手+传输：</strong>SecureCRT Send Ymodem选.bin文件→发第0包（SOH+128字节）含文件名和大小→解析后擦除APP_B区→回ACK再发'C'→从1号包起每包1024字节+2字节CRC16-CCITT→STM32独立算CRC→通过回ACK写入Flash，失败回NAK触发SecureCRT重发→全部发完后EOT握手（两次）+空包确认传输完毕。</p><p><strong>阶段三——写标志位+复位：</strong>EEPROM写BOOT_TARGET=0x01（下次启动APP_B）+ UPDATE_STATUS=0xFF（完成）→NVIC_SystemReset()软件复位。Bootloader上电读EEPROM BOOT_TARGET→0x00跳APP_A、0x01跳APP_B→关全局中断→设MSP/PC→跳转。</p><p><strong>阶段四——看门狗回滚：</strong>APP_B启动后5秒内没喂够IWDG→看门狗复位→Bootloader检测复位源为IWDG而非POR→读BOOT_COUNT→连续失败≥3次强制改BOOT_TARGET回0x00跳APP_A。</p>` },
      { id: "ri-26", tags: ["OTA","CRC","校验","高频"], q: "[项目] CRC校验怎么保证数据传输不出错？每包的具体过程？三层校验机制？", a: `<p><strong>第一层——BLE链路层CRC：</strong>KT6368 BLE无线传输自带链路层24位CRC，每个空中包都带校验值，接收端硬件自动校验。校验失败自动丢弃并请求重传。硬件实现，不占CPU。只能保证"BLE空中这一段"正确。</p><p><strong>第二层——Ymodem协议层CRC16-CCITT（应用层端到端校验）：</strong>参数：多项式0x1021，初值0x0000，输入输出均不反转。每收到一包的1024字节后，STM32在RAM里独立计算一次CRC16，和SecureCRT发来附在包尾的2字节CRC16比对——匹配→回ACK(0x06)→按字写入Flash；不匹配→回NAK(0x15)→SecureCRT自动重发本包。CRC16能检出所有奇数个比特翻转、所有长度≤16的突发错误、99.998%长度>17的突发错误。每包独立校验——错误只重发一包而非整个256KB文件重传。</p><p><strong>第三层——EEPROM标志位兜底（防Flash写入途中断电）：</strong>EEPROM的UPDATE_STATUS在OTA开始前先写0x01（传输中），全部包写完且EOT确认后才写0xFF（完成）。如果传输中途断电——上电后Bootloader读STATUS=0x01就知道APP_B存的是半截固件→直接判定不可用→擦除APP_B→回APP_A。先写状态后写数据——和Linux文件系统journal同样思想。</p>` },
      { id: "ri-27", tags: ["OTA","EEPROM"], q: "[项目] EEPROM存哪些标志位？每个字节的含义？", a: `<table><tr><th>地址</th><th>名称</th><th>字节</th><th>含义</th></tr><tr><td>0x10</td><td>BOOT_TARGET</td><td>1</td><td>0x00=APP_A, 0x01=APP_B</td></tr><tr><td>0x11</td><td>UPDATE_STATUS</td><td>1</td><td>0x00=空闲, 0x01=传输中, 0xFF=完成</td></tr><tr><td>0x12</td><td>DEFAULT_BANK</td><td>1</td><td>当前稳定版是A还是B</td></tr><tr><td>0x13</td><td>BOOT_COUNT</td><td>1</td><td>连续启动失败计数，≥3回滚</td></tr><tr><td>0x14</td><td>IMAGE_SIZE</td><td>4</td><td>当前固件大小，小端序</td></tr></table><p>UPDATE_STATUS是整个掉电保护的核心——固件写到一半断电，下次上电Bootloader看到STATUS=0x01就知道APP_B是坏的，清空标志跳APP_A。</p>` },

      // ========== 个人项目 - 电源管理 ==========
      { id: "ri-28", tags: ["功耗","休眠","高频"], q: "[项目] 四级电源状态机怎么切换？休眠功耗<1mA怎么测？", a: `<p><strong>四级状态：</strong></p><ol><li><strong>正常：</strong>全外设开，LVGL正常亮度，MAX30102连续采样，BLE保持连接</li><li><strong>息屏（30s无操作）：</strong>背光降到5%，传感器和BLE保持</li><li><strong>休眠（再300s无操作）：</strong>enter_sleep回调依次关传感器→BLE→LCD+触摸→看门狗→MCU进STOP模式，只留RTC和按键/充电外部中断</li><li><strong>充电：</strong>检测引脚拉低→邮箱发WAKEUP_CHARGE→idle线程切换充电态禁休眠</li></ol><p>唤醒后exit_sleep反序恢复——先开看门狗、再LCD和触摸、最后BLE和传感器。顺序重要：SPI和DMA的时钟在STOP模式下停了，必须重新初始化才能恢复LCD显示。</p><p><strong>功耗测量：</strong>万用表串电池正极和VCC，mA档。正常约30mA，STOP模式实测约0.8mA（手册STOP约0.4mA+LSE 0.2mA+GPIO漏电0.2mA）。500mAh电池纯待机625h≈26天。正常使用每天亮屏2h+休眠22h≈82mAh，充一次约6天。</p>` },
      { id: "ri-29", tags: ["功耗","IPC","邮箱"], q: "[项目] 为什么唤醒通知用邮箱不用消息队列？四个唤醒源怎么区分？", a: `<p><strong>MQ每条消息1字节——</strong>四种唤醒源发的都是同一个uint8_t(1)，idle线程收到后完全不知道是谁唤醒的，只能无差别恢复。但充电唤醒和按键唤醒的处理策略应该不同——充电要进充电态禁休眠，按键的可能需要继续处理按键事件。</p><p><strong>改用邮箱：</strong>每消息4字节，定义wakeup_source_t枚举——WAKEUP_KEY=1、WAKEUP_TOUCH=2、WAKEUP_CHARGE=3、WAKEUP_WRIST=4。idle线程switch-case做差异化处理：充电直接进充电态、触摸不触发UI点击避免误触、按键可跳特定页面。MQ和邮箱在RT-Thread中底层实现非常接近——都是基于链表管理IPC消息——不存在性能差异。邮箱的设计定位是"允许传递4字节值而非复制固定大小缓冲区"，正适合需要区分来源的通知场景。</p>` },

      // ========== 个人项目 - GUI优化 ==========
      { id: "ri-p16", tags: ["GUI","LVGL","性能","高频"], q: "[项目] 页面栈怎么做到15页降到2页（87%内存）？SPI DMA怎么提帧率（40%）？", a: `<p><strong>87%内存节省：</strong>GUI Guider生成15个screen全部编译期创建，控件对象挤满SRAM。改静态页面栈——Push时创建screen，Pop时lv_obj_del递归释放子控件。任何时刻只保留栈顶和上一页共2个screen，控件内存降约87%。</p><p><strong>40%帧率提升（12→20fps）：</strong>LVGL双缓冲Partial Render——分配两个15行高的缓冲区。LVGL在Buffer1渲染当前条带时，DMA在后台把Buffer2上一条带的像素发到LCD。逐像素全屏约85ms（12fps）→ DMA流水线约50ms（20fps），提升约40%。DMA把SPI传输从CPU阻塞等待变为DMA后台搬运，CPU可以并行做渲染计算。</p>` },

      // ========== 个人项目 - 遇到的问题 ==========
      { id: "ri-p17", tags: ["调试","IPC","高频"], q: "[项目] 在项目中遇到过什么问题？具体怎么解决的？（唤醒通知+传感器周期+优先级卡顿）", a: `<p><strong>问题一——唤醒通知用MQ分不清唤醒源：</strong>息屏模式下按键/触摸/充电/抬腕四种操作都能唤醒手表，MQ每条消息只传1字节——四种源发的都是同一个1，idle线程收后不知道是谁唤醒的。改用RT-Thread邮箱替代MQ——每消息4字节传枚举值（KEY=1/TOUCH=2/CHARGE=3/WRIST=4），idle线程switch-case做差异化处理。</p><p><strong>问题二——传感器轮询周期和注释不一致，实际读IMU频率比预期慢十倍：</strong>基准延时500ms→IMU条件++imu_tick>=2→2×500ms=1秒才读一次，注释标的却是"每100ms"——差了十倍。另外AHT20每2秒触发80ms转换等待（os_thread_delay_ms阻塞），排在后面的传感器数据晚80ms才更新。解决：基准延时降为50ms→废弃三个独立静态计数器→改为单一计数器取模分频（tick%2→IMU 100ms/tick%10→心率500ms/tick%40→温湿度2s），所有传感器基于同一时间基准。</p><p><strong>问题三——LVGL被传感器I2C抢占导致画面卡顿：</strong>原来传感器优先级高于LVGL→每次I2C忙等时LVGL定时到了也无法渲染→画面每0.5秒卡一次。解决：LVGL提最高优(7)、sensor降低优(11)。LVGL苏醒时不管sensor在做什么立刻抢占CPU。sensor数据晚十几ms更新功能无影响——UI下一次500ms刷新时自然拿到最新值。</p>` },

      // ========== 面试官追问 ==========
      { id: "ri-p18", tags: ["追问","I2C","GPIO"], q: "[追问] 软件I2C怎么实现的？为什么不用硬件I2C？", a: `<p><strong>实现：</strong>用GPIO开漏输出+os_udelay微秒延时模拟时序。起始条件先拉低SDA再拉低SCL，停止条件先释放SCL再释放SDA。发送字节从高位起逐位输出、每拉低SCL后延时再拉高形成时钟脉冲，第9位释放SDA读ACK。</p><p><strong>为什么不用硬件I2C：</strong>STM32F4的硬件I2C有已知Bug——Slave拉低SCL导致总线死锁后不会自动恢复，整个I2C总线挂死。软件I2C移植性好——换MCU只改GPIO和延时，不用重新配寄存器。缺点：os_udelay忙等期间不关中断→被抢占时位时序可能被打断（传感器线程优先级已降到11，对I2C影响是插入额外延迟而非翻转位值，通信不会出错）。</p>` },
      { id: "ri-p19", tags: ["追问","DMA","ADC"], q: "[追问] DMA乒乓缓冲怎么工作的？为什么比单缓冲好？", a: `<p><strong>实现：</strong>分配64半字连续缓冲区——前32半字Buffer0、后32半字Buffer1。ADC通过DMA循环模式持续往这填采样值。DMA填满前32半字触发半满中断→CPU立刻处理Buffer0的数据（算均值/转电压）。DMA继续往后32半字填数据，完全不受CPU处理Buffer0的影响。填满Buffer1触发全满中断→CPU处理Buffer1。如此循环。</p><p>单缓冲：ADC采样完一批→CPU处理→CPU处理完再启动下一批。CPU处理期间ADC停等。乒乓缓冲下DMA永远在采样，CPU永远在处理已完成半区，两不阻塞。CPU只在半满和全满两个中断各做一次32点均值运算，其余时间完全释放。</p>` },
      { id: "ri-p20", tags: ["追问","迁移","GD32"], q: "[追问] GD32F405和STM32F411的代码迁移需要改哪些？", a: `<p>只需改系统抽象层的<strong>8个</strong>hal_*_stm32.c文件和1个board_watch1.h引脚定义文件。每个_stm32.c改成_gd32.c，里面调GD32固件库替代STM32 HAL——gpio_init()替代HAL_GPIO_Init()、spi_init()替代HAL_SPI_Init()。外设寄存器基地址一样（ARM Cortex-M标准映射0x40000000），只是库函数名和参数枚举值不同。board_watch1.h改引脚定义宏——PA1还是PA1。</p><p>上层drivers、services、app三个目录共<strong>50+文件零改动</strong>。换芯片工作量约2-3天。约80%代码直接复用。</p>` },
      { id: "ri-p21", tags: ["追问","SRAM","栈"], q: "[追问] SRAM够用吗？线程栈大小怎么定的？为什么选RT-Thread？", a: `<p><strong>SRAM使用：</strong>LVGL帧缓冲双缓冲每块240×15×2+内部对象管理≈22KB、六个线程栈（LVGL 7KB+sensor 1KB+ble 1KB+idle 256B+stop 512B+key 256B）≈10KB、内核≈4KB、总计≈36-40KB。GD32F405有192KB SRAM，剩150KB+余量。</p><p><strong>栈大小确定：</strong>编译时启用RT_USING_OVERFLOW_CHECKER→运行时list_thread看max used百分比→留30%余量作为最终值。</p><p><strong>为什么选RT-Thread而非FreeRTOS：</strong>RT-Thread组件生态更完整——设备框架/文件系统/网络协议栈/finsh Shell命令行内核自带。finsh调试阶段极有价值——串口终端敲list_thread看栈使用率、free看内存分布。而且我用OSAL封装了RT-Thread API——将来换FreeRTOS只改OSAL层5个.c文件，上层代码不动。</p>` },
      { id: "ri-p22", tags: ["追问","软硬件"], q: "[追问] 在这个项目中你既是嵌入式开发又涉及硬件选型，软硬件边界怎么划分？", a: `<p>硬件侧我做的是外设选型（MAX30102/MPU6050/ST7789/KT6368/AHT20）和原理图评审——确认I2C地址不冲突、SPI片选独立、中断引脚够用。软件侧我负责全部固件——从启动代码到LVGL UI到BLE协议栈到OTA。</p><p><strong>软硬件协作的典型场景：</strong>比如MAX30102的INT引脚——硬件上拉到MCU的GPIO，软件配置为下降沿中断。调试时发现中断偶尔不触发→示波器量INT引脚→发现是OD输出+上拉电阻偏大导致上升沿太慢→加小电阻解决。这个问题本质上是软硬件边界不清晰——硬件觉得"拉个电阻就行"，软件觉得"中断应该能触发"，实际是信号完整性卡在中间。现在我评审原理图时会专门关注开漏引脚的上升时间。</p>` }
