const DATA_RTTHREAD = [
  {
    id: "os-rtos", name: "操作系统与RTOS", icon: "⚙️",
    questions: [
      { id: "rtos-36", tags: ["RT-Thread","内核","高频"], q: "RT-Thread 中 rt_container_of / rt_list_entry 宏的实现原理？", a: `<p><strong>rt_list_entry 是 RT-Thread 最核心的宏之一</strong>，用于从链表节点指针反推包含它的父结构体，是 C 语言面向对象编程的基石。</p><pre><code class="language-c">#define rt_list_entry(node, type, member) \\
    rt_container_of(node, type, member)

#define rt_container_of(ptr, type, member) \\
    ((type *)((char *)(ptr) - (unsigned long)(&((type *)0)->member)))</code></pre><p><strong>分步解析：</strong></p><ol><li><code>(type *)0</code>：将地址0强制转换为 type* 类型——这是一个"虚拟"结构体，从地址0开始</li><li><code>->member</code>：访问该虚拟结构体的 member 成员→<code>&</code> 取地址→得到 member 在 type 中的<strong>偏移量</strong></li><li><code>(char *)(ptr) - 偏移量</code>：用成员的实际地址减去偏移量→得到结构体的实际起始地址</li><li>最后强制转换为 <code>type*</code> 类型，得到正确的结构体指针</li></ol><p><strong>为什么用地址0？</strong>因为结构体从地址0开始，成员地址就等于偏移量，巧妙解决了"不知道基地址但需要偏移量"的问题。这个宏在 Linux 内核中叫 container_of，思想完全相同。</p>` },
      { id: "rtos-37", tags: ["RT-Thread","内核","高频"], q: "RT-Thread 线程栈初始化(rt_hw_stack_init)做了什么？栈帧的布局是怎样的？", a: `<p><strong>栈帧在内存中的布局（从高地址到低地址）：</strong></p><pre><code class="language-c">高地址(栈底)
0x20001000 ┌─────────────────┐ <-- stack_addr
          │  未使用栈空间     │
0x200011C0 ├─────────────────┤ <-- sp (初始化后的栈指针)
          │ r4 ~ r11         │ 手动保存寄存器(32字节)，初始化为0xdeadbeef
0x200011E0 ├─────────────────┤
          │ r0 (parameter)   │ 线程入口参数
          │ r1 = 0           │
          │ r2 = 0           │
          │ r3 = 0           │
          │ r12 = 0          │
          │ lr (texit)       │ 链接寄存器→退出函数
          │ pc (tentry)      │ 程序计数器→线程入口函数
          │ psr = 0x01000000 │ Thumb状态
低地址(栈顶) └─────────────────┘</code></pre><p><strong>关键设计：</strong></p><ul><li>r0 存线程参数→线程第一次运行时自动以 parameter 作为参数调用 entry</li><li>lr 设为线程退出函数→线程 return 时自动跳转清理函数，防止跑飞</li><li>pc 设为入口函数→首次切换到此线程时从这里开始执行</li><li>psr=0x01000000→bit24=1 表示 Thumb 指令集状态（Cortex-M 必须）</li><li>所有寄存器初始化为 0xdeadbeef →调试时一眼识别未初始化栈</li></ul><p>栈帧分为两部分：<strong>exception_stack_frame</strong>（r0-r3,r12,lr,pc,psr—硬件自动出入栈）和 <strong>stack_frame</strong>（r4-r11—软件手动保存恢复）。这完美对应 Cortex-M 的异常入栈机制。</p>` },
      { id: "rtos-38", tags: ["RT-Thread","内核"], q: "RT-Thread 线程退出(rt_thread_exit)时做了什么？静态和动态线程的区别？", a: `<p><strong>rt_thread_exit 执行流程：</strong></p><ol><li>获取当前线程→关中断</li><li>执行线程清理回调 <code>_thread_cleanup_execute</code></li><li>从调度器就绪队列移除→状态设为 RT_THREAD_CLOSE</li><li>分离线程内置定时器 <code>rt_timer_detach</code></li><li><strong>关键分支——静态 vs 动态线程：</strong></li></ol><table><tr><th>线程类型</th><th>处理方式</th><th>标志</th></tr><tr><td>静态线程(rt_thread_init)</td><td>直接 <code>rt_object_detach</code> 分离对象</td><td>RT_Object_Class_Static</td></tr><tr><td>动态线程(rt_thread_create)</td><td>加入 <code>rt_thread_defunct</code> 待销毁链表→由idle线程后续释放内存</td><td>无Static标志</td></tr></table><p><strong>为什么动态线程不能直接释放？</strong>当前函数运行在线程自己的栈上——如果直接 rt_free 释放线程的栈和TCB，后续代码将访问已释放的内存，导致崩溃。idle线程在另一个栈上执行，可以安全地释放。</p><p><strong>lr 设为 rt_thread_exit 的意义：</strong>即使线程函数意外 return，也会自动跳转到 rt_thread_exit 做安全清理，不会跑飞执行未知代码。</p>` },
      { id: "rtos-39", tags: ["RT-Thread","内核","高频"], q: "RT-Thread 线程睡眠(rt_thread_sleep)的完整流程？", a: `<p><strong>rt_thread_sleep 完整时序：</strong></p><ol><li><strong>关中断</strong>→获取当前线程→验证线程对象有效性</li><li><strong>挂起线程</strong> <code>rt_thread_suspend(thread)</code>：从就绪队列移除，状态→RT_THREAD_SUSPEND</li><li><strong>设置并启动定时器</strong>：<code>rt_timer_control</code> 设置超时时间→<code>rt_timer_start</code> 将定时器插入跳表。超时回调为 <code>rt_thread_timeout</code></li><li><strong>开中断→调用 rt_schedule()</strong>：当前线程在此暂停，CPU 切换到其他就绪线程</li><li>[线程在此处挂起...]</li><li><strong>定时器超时→rt_thread_timeout 被调用</strong>：设置 error=-RT_ETIMEOUT→从挂起列表移除→重新插入就绪队列→rt_schedule()</li><li><strong>线程被重新调度</strong>：从 rt_schedule() 之后继续执行</li><li><strong>清理</strong>：检查 thread->error==-RT_ETIMEOUT 则清零→返回 RT_EOK</li></ol><p><strong>关键设计：</strong>每个线程有内置定时器(thread_timer)，复用一个定时器对象避免频繁创建销毁。超时回调是统一的 rt_thread_timeout，参数就是线程本身。</p>` },
      { id: "rtos-40", tags: ["RT-Thread","内核","高频"], q: "RT-Thread 定时器跳表(Skip List)的插入算法？RT_TIMER_SKIP_LIST_LEVEL 的作用？", a: `<p><strong>跳表是多层级索引链表</strong>，上层节点稀疏（跳得快），下层节点密集（找得准），查找/插入复杂度从 O(n) 降到 O(log n)。</p><p><strong>插入流程（rt_timer_start 核心逻辑）：</strong></p><ol><li>从最底层(第0层)开始，遍历当前层查找插入位置</li><li>核心比较：<code>(t->timeout_tick - timer->timeout_tick) < RT_TICK_MAX/2</code>→找到比新定时器超时时间晚的节点即停止。相同超时时间则继续向后（先插入先执行）</li><li>找到后在当前层插入→通过随机数决定是否插入更高层（类似抛硬币）</li><li><strong>必定插入最底层</strong>保证有序性</li></ol><p><strong>RT_TIMER_SKIP_LIST_LEVEL 影响：</strong></p><table><tr><th>层级</th><th>数据结构</th><th>插入复杂度</th><th>空间</th><th>适用</th></tr><tr><td>1(默认)</td><td>退化普通双向链表</td><td>O(N)</td><td>最小</td><td>定时器<30个</td></tr><tr><td>2~3</td><td>多层级跳表</td><td>~O(log N)</td><td>稍大</td><td>定时器>100个</td></tr></table><p><strong>溢出处理：</strong>差值用无符号运算，配合 RT_TICK_MAX/2 阈值巧妙区分"真的早"还是"溢出后看起来晚"。</p>` },
      { id: "rtos-41", tags: ["RT-Thread","内核","高频"], q: "rt_timer_check（硬定时器）和 rt_soft_timer_check（软定时器）的核心区别？回调分别在什么上下文执行？", a: `<table><tr><th>特性</th><th>rt_timer_check（硬）</th><th>rt_soft_timer_check（软）</th></tr><tr><td>执行上下文</td><td><strong>中断上下文</strong>（SysTick ISR 中调用）</td><td><strong>线程上下文</strong>（timer_thread 中执行）</td></tr><tr><td>中断处理</td><td><strong>全程关中断</strong></td><td>执行回调时<strong>开中断</strong></td></tr><tr><td>回调限制</td><td>不能阻塞、不能调用睡眠函数、必须极短</td><td>可执行复杂操作、可阻塞等待</td></tr><tr><td>实时性</td><td>高（立即响应）</td><td>中（受线程调度影响）</td></tr></table><p><strong>软定时器关键设计：</strong></p><ul><li>执行回调前先 <code>rt_hw_interrupt_enable(level)</code> 开中断→允许中断嵌套，不阻塞系统</li><li>通过 <code>soft_timer_status</code> 状态机（RT_SOFT_TIMER_IDLE/BUSY）管理并发</li><li>回调执行完毕后重新关中断→检查是否需要重启周期性定时器</li><li>软定时器的超时不会阻塞硬实时中断，适合长时间操作</li></ul><p><strong>共同点：</strong>两者都在检查前关中断保证链表操作原子性，都将超时定时器从跳表取出放入临时列表（防止回调中修改定时器导致链表遍历异常）。</p>` },
      { id: "rtos-42", tags: ["RT-Thread","内核"], q: "rt_interrupt_nest 变量的作用？如何判断当前是中断上下文还是线程上下文？", a: `<p><strong>rt_interrupt_nest 是全局中断嵌套计数器。</strong>每次进入ISR调用 <code>rt_interrupt_enter()</code>→nest++；每次退出ISR调用 <code>rt_interrupt_leave()</code>→nest--。</p><pre><code class="language-c">void rt_os_tick_callback(void) {
    rt_interrupt_enter();    // nest++，标记进入中断上下文
    rt_tick_increase();      // 执行 tick 处理（检查定时器等）
    rt_interrupt_leave();    // nest--，标记退出中断上下文
}</code></pre><p><strong>判断上下文的方法：</strong></p><ul><li><code>rt_interrupt_get_nest() > 0</code>→中断上下文</li><li><code>rt_interrupt_get_nest() == 0</code>→线程上下文</li></ul><p><strong>为什么需要这个判断？</strong>某些操作（如内存分配、互斥锁获取、线程睡眠）不能在中断上下文中执行。内核函数通过这些API检查当前上下文并做出相应处理。RT_DEBUG_NOT_IN_INTERRUPT 宏在 debug 模式下会断言检查。</p>` },
      { id: "rtos-43", tags: ["RT-Thread","内核"], q: "rt_object_init 为什么把新对象插在容器链表头部？", a: `<p><strong><code>rt_object_init</code>使用<code>rt_list_insert_after(&information->object_list, &object->list)</code>，因此后创建的对象位于容器链表前部。</strong></p><p>初始: [头节点]→空→插入A: [头节点]→[A]→插入B: [头节点]→[B]→[A]→插入C: [头节点]→[C]→[B]→[A]</p><p><strong>准确理解：</strong></p><ol><li><strong>头插是O(1)</strong>，实现直接、无需维护额外顺序。</li><li><strong>尾插也可以是O(1)</strong>：RT-Thread的<code>rt_list_t</code>是循环双向链表，头节点保存<code>prev</code>，调用<code>rt_list_insert_before</code>即可在尾部常数时间插入。因此“尾插必须O(n)遍历”不是这里的理由。</li><li><strong>对象查找不依赖创建顺序</strong>：<code>rt_object_find</code>按名称遍历，头插主要体现内核实现约定，并使后创建对象先被遍历。</li></ol><p>面试时应区分“当前源码采用头插”与“数据结构只能头插”。</p>` },
      { id: "rtos-44", tags: ["RT-Thread","IPC","高频"], q: "RT-Thread 邮箱(mailbox)和消息队列(message queue)的核心区别？如何选型？", a: `<table><tr><th>特性</th><th>邮箱(mailbox)</th><th>消息队列(msg queue)</th></tr><tr><td>数据大小</td><td>固定一个<code>rt_ubase_t</code>（32位MCU上通常4字节）</td><td>创建时指定固定消息大小</td></tr><tr><td>数据结构</td><td>环形缓冲区(值数组)</td><td>预分配消息池+空闲链表+消息链表</td></tr><tr><td>传递方式</td><td>值传递（也可把指针值作为消息）</td><td>按配置大小拷贝数据</td></tr><tr><td>内存管理</td><td>简单（无每条消息动态分配）</td><td>预分配池，发送时从空闲链表取块</td></tr><tr><td>效率</td><td>传递一个机器字，开销小</td><td>需要数据拷贝</td></tr></table><p><strong>选型建议：</strong></p><ul><li><strong>用邮箱</strong>：传递命令码、状态标志或受控生命周期的指针。宽度随架构的<code>rt_ubase_t</code>而定，不能在所有平台都写死为4字节。</li><li><strong>用消息队列</strong>：传递固定大小结构体（传感器读数、事件结构）。数据拷贝意味着发送完成后可复用源缓冲区，所有权更清晰。</li><li><strong>指针传递的风险</strong>：邮箱只复制指针值，不会复制指向的数据，必须定义谁分配、谁释放以及接收前能否修改。</li></ul>` },
      { id: "rtos-45", tags: ["RT-Thread","IPC","高频"], q: "rt_mq_create 中空闲消息链表是如何构建的？为什么用头插法？", a: `<p><strong>消息队列的内存布局：</strong>每个消息块 = <code>sizeof(struct rt_mq_message)</code> 的消息头 + msg_size 字节的数据区。整个消息池 = max_msgs × (消息头+数据区)。</p><p><strong>空闲链表构建过程（头插法）：</strong></p><ol><li>初始 free=NULL</li><li>第1次：head=消息块0, head->next=NULL, free=消息块0</li><li>第2次：head=消息块1, head->next=消息块0, free=消息块1</li><li>第3次：head=消息块2, head->next=消息块1, free=消息块2</li></ol><p>最终：<strong>空闲链表 free → 消息块2 → 消息块1 → 消息块0 → NULL</strong></p><p><strong>为什么头插法？</strong>O(n)→空闲链表构建只需一次遍历，O(1)插入每次都是常数时间。尾插法需要每次遍历到链尾，总复杂度 O(n²)。</p>` },
      { id: "rtos-46", tags: ["RT-Thread","IPC","进阶"], q: "rt_mq_send_wait 中消息队列从空到有3条消息的链表构建过程是怎样的？", a: `<p><strong>初始状态：</strong>空闲链表 free→m3→m2→m1→NULL，消息队列 head=NULL, tail=NULL</p><p><strong>插入 m3（第一条消息）：</strong></p><ul><li>m3->next=NULL→tail=m3→head=m3（因为head之前是NULL）</li></ul><p><strong>插入 m2（第二条消息）：</strong></p><ul><li>m2->next=NULL→<strong>tail->next=m2</strong>（当前tail是m3）→m3->next=m2→tail=m2</li></ul><p><strong>插入 m1（第三条消息）：</strong></p><ul><li>m1->next=NULL→<strong>tail->next=m1</strong>（当前tail是m2）→m2->next=m1→tail=m1</li></ul><p><strong>最终：</strong>head→m3→m2→m1(next=NULL)←tail。每次插入时：新消息的next设为NULL→将当前尾部的next指向新消息→更新tail。整个操作为 O(1)，不需要遍历。head始终指向最早插入的消息，tail始终指向最新插入的消息。</p>` },
      { id: "rtos-47", tags: ["RT-Thread","IPC","进阶"], q: "rt_mb_send_wait 和 rt_mq_send_wait 阻塞发送的完整流程？超时后如何恢复？", a: `<p><strong>阻塞发送流程（邮箱/消息队列逻辑相似）：</strong></p><ol><li>关中断→检查邮箱/队列是否满</li><li><strong>若满且 timeout=0</strong>（非阻塞）：立即返回 -RT_EFULL</li><li><strong>若满且 timeout>0</strong>（阻塞等待）：</li><ul><li>挂起当前线程到发送者挂起列表</li><li>记录当前 tick→启动线程内置定时器（超时时间=timeout）</li><li>开中断→<strong>rt_schedule() 切换到其他线程</strong></li><li>[线程在此挂起...]</li></ul><li><strong>被唤醒（两种情况）：</strong></li><ul><li>情况A：接收者取走数据→邮箱有空位→内核从发送者挂起列表唤醒线程→thread->error=RT_EOK→跳出while循环→执行发送</li><li>情况B：<strong>超时→rt_thread_timeout</strong> 被调用→thread->error=-RT_ETIMEOUT→线程被插入就绪队列→重新调度到线程→检查 error≠RT_EOK→<strong>直接返回 -RT_ETIMEOUT</strong></li></ul><li><strong>如果 timeout>0</strong>（有限等待）：恢复后重新计算剩余超时时间 timeout-=已等待tick。若 timeout<0 则清零（处理被其他事件提前唤醒但非满的情况）</li></ol><p><strong>关键设计：</strong>线程内置定时器复用+计算剩余超时（支持被虚假唤醒后继续等待）。</p>` }
    ]
  }
];
