const DATA_RESUME = [
  {
    id: "resume-interview",
    name: "简历面试与项目深挖",
    icon: "📋",
    questions: [
      // ========== 海康威视实习 - GTC平台化 ==========
      { id: "ri-1", tags: ["海康","平台化","高频"], q: "[海康] GTC模块平台化的核心思想是什么？解决了什么问题？", a: `<p>核心思想：通过<strong>编译时条件隔离 + 运行时动态适配</strong>，让同一份GTC时间戳驱动代码支持多款TI SoC（J721E/J721S2/J784S4）和不同CPU核（ARM Cortex-A/C66x DSP/Cortex-R），上层调用<code>hal_gtc_getms()</code>无需关心底层差异。</p><p><strong>三个关键设计：</strong></p><ul><li><strong>多SoC编译隔离</strong>：<code>#if defined(SOC_J721E)</code>包含不同的寄存器基址头文件和CSL库路径，避免错误编译</li><li><strong>地址映射差异抽象</strong>：J721E上C66x DSP核需通过RAT做地址转换，代码中通过<code>hal_get_cpuid()</code>运行时判断CPU核类型，动态设置<code>uG_gtc_base</code></li><li><strong>时钟频率统一</strong>：不同SoC默认时钟可能不同，通过<code>hal_clk_getrate()</code>获取+<code>hal_clk_setrate()</code>统一到200MHz</li></ul><p><strong>效果：</strong>新增芯片只需在初始化增加对应的基址映射逻辑，上层代码零改动。</p>` },
      { id: "ri-2", tags: ["海康","平台化","进阶"], q: "[海康] 在J721E上C66x DSP核不能直接访问GTC寄存器，你是如何解决的？", a: `<p>J721E上C66x DSP核不能直接访问GTC物理地址（0xA90000），必须通过RAT（Region Address Translator）把一段空闲地址空间映射到真实寄存器地址。</p><p><strong>解决方案——运行时动态基址：</strong></p><ol><li>默认基址设为<code>GTC0_GTC_CFG1_BASE</code>（0xA90000）</li><li>编译J721E时通过<code>hal_get_cpuid()</code>获取当前CPU核ID</li><li>如果是C66x_0或C66x_1：先配置RAT映射（把0x200000000映射到0xA90000），再把<code>uG_gtc_base</code>改为0x200000000</li><li>其他核（ARM等）直接用真实地址0xA90000</li><li>J721S2/J784S4无此问题，基址保持0xA90000</li></ol><p>之后所有寄存器读写基于<code>uG_gtc_base</code>，不写死地址、不用<code>#ifdef</code>。同一份代码在所有SoC、所有核上都能正确读到GTC值。</p>` },
      { id: "ri-3", tags: ["海康","平台化","进阶"], q: "[海康] GTC时间同步在主从设备上行为不一致，你是怎么设计的？", a: `<p><strong>问题：</strong>车载场景中主板(Master)是时间源、从板(Slave)需要同步到主板。如果直接在<code>hal_gtc_getus</code>里写<code>return 硬件时间+补偿值</code>，主板不需要补偿但要写时间出去，逻辑耦合混乱。</p><p><strong>解决——分离职责：</strong></p><ul><li><strong>核心函数</strong><code>hal_gtc_getus</code>只做一件事：读取硬件计数÷时钟频率=原始本地时间</li><li><strong>时间同步</strong>通过独立的条件编译块叠加：<code>#if defined(CONFIG_HW_AE_B50038_S) || defined(CONFIG_HW_AE_B50038_M)</code>时额外加<code>CPTS_DIFF_GTC</code>寄存器的补偿值</li><li>从板：差值寄存器已写入主板与本地的时间差，直接加</li><li>主板：差值寄存器为0，或不编入此宏</li><li>主板另有一个独立线程<code>stl_timesync_main</code>负责把自己的GTC时间写入共享内存</li></ul><p>核心时间读取逻辑不受同步逻辑污染，不同硬件形态通过编译宏清晰配置。</p>` },
      { id: "ri-4", tags: ["海康","测试","进阶"], q: "[海康] 平台化后如何验证GTC时间准确性？STL自测框架怎么做的？", a: `<p><strong>仅读寄存器值不够</strong>——你知道计数器在递增，但不知道递增速度对不对。需要端到端功能测试。</p><p><strong>借助STL（Self-Test Library）框架写测试任务：</strong></p><ol><li><code>hal_gtc_getms()</code>获取开始时间→系统<code>sleep(1000)</code>→再获取结束时间→差值应=1000±1ms</li><li>同样测试us接口，同时对比OS tick（sys_pthread_tick）做交叉验证</li><li>us差值应在1,000,000±1000范围，OS tick差值应在1000±1范围</li></ol><p><strong>为什么对比OS tick？</strong>OS tick由另一个独立定时器驱动，两个独立时钟都符合预期→可信度高。如果GTC和OS tick都漂移但方向一致→系统时钟源可能有问题。</p><p><strong>效果：</strong>每个平台移植后跑STL用例自动验证准确性。早期发现过时钟频率获取失败导致的时间漂移，及时修复。测试用例已集成到CI流程。</p>` },
      { id: "ri-5", tags: ["海康","平台化"], q: "[海康] GTC模块使用early_init宏注册，为什么需要早期初始化？", a: `<p><code>early_init(hal_gtc_init);</code>将GTC驱动注册到系统启动早期阶段执行。平台化通用初始化框架定义了模块的初始化顺序，GTC作为时间戳基础设施必须在其他依赖时间的模块（日志、定时器、STL测试框架等）之前完成初始化。</p><p>如果GTC在后期才初始化，依赖它的模块可能在启动时读到未初始化的时钟值（全0或随机值），导致超时判断异常。early_init机制保证启动顺序的确定性。</p>` },

      // ========== 海康威视实习 - Tessy单元测试 ==========
      { id: "ri-6", tags: ["海康","Tessy","测试"], q: "[海康] Tessy单元测试覆盖了哪些模块？发现了什么有价值的Bug？", a: `<p><strong>覆盖模块：</strong>secure（加解密API）、memory（内存分配/释放/地址对齐）、dmaheap（DMA缓冲池分配回收）、network（Socket封装/组播加入离开）、diagnostic（日志输出/assert处理）。</p><p><strong>最有价值的Bug——RSA签名验证中的隐式转换：</strong></p><ul><li>Tessy发现分支覆盖率只有85%，一个<code>if(pad_len<0)</code>分支不可达</li><li>分析：<code>pad_len</code>是<code>int32_t</code>，但来自被调函数返回的<code>uint32_t</code>，隐式转换后永远非负→if条件永远为假</li><li>修复：修改函数原型或增加显式范围检查</li><li>若不修复：畸形输入下可能发生数组越界</li></ul><p>其他发现的典型问题：分支不可达、资源泄漏（未释放的DMA缓冲区）、整型溢出等。</p>` },
      { id: "ri-7", tags: ["海康","Tessy","进阶"], q: "[海康] Tessy测试中分支不可达和资源泄漏你是怎么发现的？", a: `<p>Tessy通过<strong>代码插桩</strong>记录每次测试执行的路径。生成覆盖率报告后，未覆盖的分支标记为黄色/红色。分析这些分支：(1)确认测试用例是否遗漏该路径→补充用例 (2)确认分支是否真正不可达（逻辑死代码）→修复源代码。</p><p>资源泄漏检测：Tessy可跟踪<code>malloc/free</code>的配对情况。在dmaheap模块中发现某个错误返回路径释放了pool但未释放pool->chunks数组。修复方式是统一用goto cleanup模式确保所有出口都走释放逻辑。</p>` },

      // ========== 海康威视实习 - DTS ==========
      { id: "ri-8", tags: ["海康","DTS","Linux"], q: "[海康] 基于DTS完成硬件资源注册与中断配置的流程？以SPI为例", a: `<p><strong>完整流程：</strong></p><ol><li><strong>DTS节点编写</strong>：<code>reg</code>（基址+长度）、<code>interrupts</code>（<控制器类型 中断号 触发方式>，如<GIC_SPI 45 IRQ_TYPE_EDGE_RISING>）、<code>clocks</code>、<code>pinctrl-0</code></li><li><strong>驱动匹配</strong>：<code>of_match_table</code>中<code>compatible</code>字符串与DTS的<code>compatible</code>属性匹配→probe被调用</li><li><strong>资源获取</strong>：<code>platform_get_resource(pdev, IORESOURCE_MEM, 0)</code>获取寄存器基址 → <code>devm_ioremap_resource</code>映射</li><li><strong>中断注册</strong>：<code>platform_get_irq(pdev, 0)</code>→<code>devm_request_irq</code>绑定ISR（注意ISR中不能睡眠）</li></ol><p><strong>调试手段：</strong><code>cat /proc/interrupts</code>查看中断计数、<code>cat /proc/device-tree/spi@xxx/interrupts</code>验证DTS解析结果、<code>dtc -I dtb -O dts</code>反编译dtb验证。</p>` },
      { id: "ri-9", tags: ["海康","DTS","调试"], q: "[海康] DTS中断配置遇到过什么问题？如何排查？", a: `<p><strong>遇到过中断号写错导致不触发的问题。</strong>现象是驱动probe成功但ISR从未被调用。</p><p><strong>排查步骤：</strong></p><ol><li>对比芯片手册中该外设的中断线编号与DTS中<code>interrupts</code>第二个cell是否一致</li><li>查看<code>/proc/interrupts</code>看中断计数是否为0</li><li>确认引脚复用（pinctrl）配置正确</li><li>确认驱动是否成功调用<code>devm_request_irq</code>（检查返回值）</li><li>如果是共享中断，确认中断控制器支持且所有共享设备都正确处理了"不是我的中断"的情况</li></ol><p>定位后修正DTS中断号即可。另一个常见问题是<code>reg</code>地址空间与其他设备重叠，通过检查<code>reserved-memory</code>节点解决。</p>` },

      // ========== 海康威视实习 - U-Boot快启优化 ==========
      { id: "ri-10", tags: ["海康","U-Boot","OTA","高频"], q: "[海康] U-Boot快启优化你做了哪些工作？启动时间缩短了多少？", a: `<p><strong>背景：</strong>车载产品支持OTA，U-Boot是OTA升级流程的关键环节，启动速度直接影响升级窗口和回滚停机时间。</p><p><strong>瓶颈分析：</strong>用<code>get_timer()</code>埋点打印各阶段耗时→MMC初始化400ms、网络驱动300ms、USB初始化200ms、还有不必要的SD卡槽检测。</p><p><strong>三项优化：</strong></p><ul><li><strong>裁剪冗余驱动</strong>：OTA升级包在进U-Boot前已下载到eMMC，不需要网络和USB。关闭<code>CONFIG_NET</code>和<code>CONFIG_USB</code>及关联命令，镜像缩小、初始化更快</li><li><strong>减少非必要外设初始化</strong>：板上有两个MMC控制器（eMMC+SD卡），SD卡在U-Boot阶段完全不用，直接在设备树删掉SD卡节点（注意：disable不够——MMC驱动遍历所有节点仍会尝试访问寄存器；需彻底删节点）</li><li><strong>精简设备树</strong>：禁用多余的UART、I2C触摸屏、音频等节点，简化pinctrl只保留必需引脚组</li></ul><p><strong>踩坑：</strong>关掉网络后环境变量保存失败——因为MAC地址存储依赖网络子系统。换方案：直接从SoC OTP读MAC地址。</p><p><strong>最终效果：</strong>启动从<strong>1.2s降到0.7s，优化超过40%</strong>，镜像减少120KB。升级写入有更多时间校验，回滚停机时间缩短1/3。</p>` },
      { id: "ri-11", tags: ["海康","U-Boot","进阶"], q: "[海康] U-Boot优化中把SD卡节点disable后eMMC也初始化失败了，为什么？怎么解决的？", a: `<p><strong>根因：</strong>该MMC驱动在probe时会遍历设备树中所有MMC控制器节点（包括disabled的），对每个节点尝试读取寄存器来判断是否存在。SD卡节点虽然disabled但仍在设备树中，驱动仍尝试访问SD卡的MMC控制器寄存器——但SD卡槽是空的或未上电→读取寄存器返回异常→驱动误判为错误→整个MMC子系统初始化失败→eMMC也受影响。</p><p><strong>解决：</strong>不是disable节点（status="disabled"），而是直接将SD卡节点从设备树中删除。驱动遍历时就完全看不到这个节点，不会去碰它。</p><p><strong>教训：</strong>disable和删除在设备树语义上不同——disable表示"硬件存在但软件不使用"，删除表示"硬件不存在"。对于会主动遍历所有节点的驱动，需要根据实际情况选择正确的方式。</p>` },

      // ========== 经纬恒润实习 ==========
      { id: "ri-12", tags: ["经纬恒润","UDS","Bootloader","高频"], q: "[经纬恒润] 描述一下基于UDS on CAN的Bootloader刷写流程", a: `<p><strong>完整刷写流程：</strong></p><ol><li><strong>诊断会话控制(0x10 0x03)</strong>：切换到扩展会话，TesterPresent(0x3E)维持会话</li><li><strong>安全访问(0x27)</strong>：请求Seed→ECU返回随机数→上位机根据Seed+内部算法计算Key→发送Key→ECU验证通过解锁</li><li><strong>下载流程</strong>：RequestDownload(0x34)→指定起始地址和数据长度→TransferData(0x36)→按块（block）发送固件数据→RequestTransferExit(0x37)→CRC完整性校验确认</li><li><strong>ECU复位(0x11)</strong>：硬复位进入新的应用程序</li></ol><p><strong>我的职责：</strong>负责上位机（VBA脚本）与BCM之间的刷写交互逻辑，实现上述流程的自动化脚本。每条诊断请求/响应的超时处理和错误重试机制都在脚本中实现。</p>` },
      { id: "ri-13", tags: ["经纬恒润","调试"], q: "[经纬恒润] 刷写过程中遇到过VBA报文冲突的问题，怎么解决的？", a: `<p><strong>问题：</strong>通过VBA发送0x22 0x01 0x12获取版本号的报文，与Normal Communication（胎压模式、钥匙模式下对应byte递增）的0x80报文发生了冲突。两个不同来源的诊断请求在同一时刻竞争CAN总线。</p><p><strong>排查：</strong>查看源码发现两种报文的发送时机产生了重叠——Normal Comm的周期发送正碰上了VBA的诊断请求。CAN ID虽然不同但都在同一总线上，仲裁后某个会延迟，且延迟后的响应时序被打乱。</p><p><strong>解决：</strong>在VBA脚本中增加标志位检查——发送诊断请求前先检查Normal Comm是否正在进行关键通信，用特定标志位（模式切换标志）来指示当前是否允许发送诊断指令。诊断请求只在安全窗口（无Normal Comm冲突风险时）发送。</p>` },
      { id: "ri-14", tags: ["经纬恒润","Polyspace","静态分析"], q: "[经纬恒润] Polyspace静态分析发现了哪些类型的Bug？", a: `<p>对BCM应用层代码（胎压监测、钥匙匹配、LIN通信）进行Polyspace检查，发现10+处问题：</p><table><tr><th>类型</th><th>数量</th><th>示例</th></tr><tr><td>未使用变量</td><td>~3处</td><td>遗留调试变量未删除</td></tr><tr><td>数组越界风险</td><td>2处</td><td><code>uint8_t buf[8]</code>访问索引8（最大下标应为7）</td></tr><tr><td>空指针解引用</td><td>1处</td><td>函数返回NULL后未检查直接使用</td></tr><tr><td>整型转换丢失符号</td><td>2处</td><td>有符号负数隐式转为无符号大数</td></tr><tr><td>死代码</td><td>2处</td><td><code>if(0)</code>或永远为真的分支</td></tr><tr><td>非初始化变量</td><td>2处</td><td>局部变量未赋初值就使用</td></tr></table><p>Polyspace的优势在于不需要实际运行代码，通过抽象解释分析所有可能的执行路径。在汽车功能安全（ISO26262）中使用MISRA C+Polyspace是标准实践。</p>` },

      // ========== 个人项目 - 系统架构设计 ==========
      { id: "ri-15", tags: ["架构","五层架构","高频"], q: "[项目] 整体架构怎么设计的？五层分别做什么？六个线程怎么分工？", a: `<p><strong>五层架构：</strong></p><ol><li><strong>应用层</strong>：创建六个线程（LVGL渲染5ms、传感器轮询50ms、BLE通信20ms、按键扫描20ms、idle电源管理50ms、stop休眠管理100ms）加一个500ms软件定时器做UI数据刷新和空闲计时</li><li><strong>服务层</strong>：全部纯C、零硬件依赖的业务逻辑——心率算法（IIR去直流+七点窗峰值检测）、血氧算法（AC/DC比值法）、电量查表、计算器引擎（中缀转后缀表达式求值）、BLE协议解析、OTA Ymodem状态机。可在PC上独立编译测试</li><li><strong>驱动层</strong>：每外设实现ops函数指针接口——IMU的imu_ops_t、显示的display_ops_t共十一类。MPU6050填一份，ST7789填一份。驱动层只依赖HAL接口头文件，不直接碰寄存器</li><li><strong>系统抽象层</strong>：OSAL封装RT-Thread API + HAL封装外设操作（GPIO/SPI/I2C/ADC/UART/RTC/WDT）。全项目仅此层8个文件含芯片寄存器代码。换芯片只改这一层</li><li><strong>硬件层</strong>：GD32厂商库和CMSIS，不修改</li></ol><p>层间 App→Service→Driver→HAL 全部直接函数调用纳秒级延迟。跨线程才用IPC——按键通知LVGL用消息队列、唤醒通知用邮箱。</p>` },
      { id: "ri-16", tags: ["架构","多态","函数指针","高频"], q: "[项目] ops结构体怎么实现多态？举例子", a: `<p>接口定义一个全是函数指针的结构体：</p><pre><code class="language-c">typedef struct {
    int32_t (*init)(void);
    bool    (*read_accel_gyro)(drv_imu_data_t *);
    bool    (*is_data_ready)(void);
} imu_ops_t;</code></pre><p>MPU6050驱动把这些指针填上寄存器读写函数，生成mpu6050_imu_ops常量。上层只拿到imu_ops_t*指针，调<code>ops->read_accel_gyro(&data)</code>时编译器通过函数指针间接跳转——这就是C语言的多态。上层代码没有一行<code>#include "mpu6050.h"</code>。换芯片只改注册表里的一行ops指针，其余代码零改动。</p>` },
      { id: "ri-17", tags: ["架构","依赖倒置","SOLID","高频"], q: "[项目] 设备注册表是什么？怎么实现依赖倒置？", a: `<p>一个全局数组g_registry[16]，启动时在board_init()把所有外设ops注入：</p><pre><code class="language-c">dev_register("imu",     &mpu6050_imu_ops);
dev_register("display", &st7789_display_ops);</code></pre><p>服务层按名称查找：<code>imu_ops_t *imu = dev_get_ops("imu");</code>，内部是for循环strcmp匹配。</p><p><strong>依赖倒置的含义：</strong>传统写法是服务层<code>#include "mpu6050.h"</code>——上层依赖具体实现，换芯片要改服务层。注册表反转了这个方向——服务层只依赖imu_ops_t抽象接口，具体是谁由board_init注入。依赖从"上层→具体"变成了"上层→抽象←具体"，这就是SOLID依赖倒置在C语言中的落地。</p><p>我最初想引入Linux的platform bus做设备注册/匹配/probe，写完伪代码发现项目只有10个外设且编译期已知，probe/match的代码量远超实际价值。最终60行注册表替代了300+行过度设计。</p>` },
      { id: "ri-18", tags: ["架构","IPC","实时性","高频"], q: "[项目] 层间直接调用和线程间消息队列怎么决策的？走过什么弯路？", a: `<p>最初想层间全用消息队列做彻底解耦。画完时序图发现一次传感器读取需要4次上下文切换——App→Service→Driver→返回路径，累积延迟对LVGL 60fps帧刷新不可接受。查阅PX4飞控和ESP-IDF源码后确认"<strong>垂直直接调用+水平消息队列</strong>"才是嵌入式实时系统的最佳实践。</p><p><strong>最终方案：</strong>同线程调用链(垂直)全部直接函数调用、纳秒级延迟；只有跨线程(水平)才用IPC——按键通知LVGL用消息队列、唤醒通知用邮箱。这纠正了我对"彻底解耦"的执念——解耦有代价（上下文切换），要在性能和可维护性之间找平衡点。</p>` },
      { id: "ri-19", tags: ["架构","高内聚低耦合","高频"], q: "[项目] 高内聚低耦合具体怎么体现？举个例说明", a: `<p><strong>高内聚——每个模块只做一件事：</strong>svc_spo2_algo.c只管PPG信号处理和心率血氧计算，用环形缓冲区管理数据，不碰GPIO和I2C。hal_i2c_stm32.c只管I2C位操作，不关心上层是温湿度传感器还是EEPROM。打开任一文件能看懂全部逻辑。</p><p><strong>低耦合——模块间只通过接口通信：</strong>svc_sensor_fusion.c通过dev_get_ops("imu")获取IMU接口，没有<code>#include "mpu6050.h"</code>。app_ui_pages.c通过svc_data_store_get_sensors()获取数据，不访问全局变量。按键线程os_mb_send(idlebreak_mb)通知idle线程，两个线程互不调用对方函数。</p><p>效果：改HAL不影响Service，加新传感器只需实现ops然后注册，不改已有代码。</p>` },
      { id: "ri-20", tags: ["架构","线程","RT-Thread","高频"], q: "[项目] 线程优先级和时间片怎么分配的？为什么LVGL最高优？", a: `<p><strong>六个线程分四个等级（数字越小优先级越高）：</strong></p><table><tr><th>线程</th><th>优先级</th><th>时间片</th><th>周期</th><th>核心工作</th></tr><tr><td>lvgl</td><td>7</td><td>15ms</td><td>5ms</td><td>lv_timer_handler帧渲染，读触摸坐标，检测触摸唤醒</td></tr><tr><td>idle_mgr</td><td>9</td><td>5ms</td><td>50ms</td><td>等idle_mq（息屏触发）和idlebreak_mb（唤醒触发）</td></tr><tr><td>stop_mgr</td><td>10</td><td>5ms</td><td>100ms</td><td>永久阻塞等stop_mq，收到后关外设进STOP模式</td></tr><tr><td>sensor</td><td>11</td><td>5ms</td><td>50ms</td><td>I2C读传感器，调血氧算法，写svc_data_store</td></tr><tr><td>ble</td><td>12</td><td>5ms</td><td>20ms</td><td>轮询BLE标志，协议解析或Ymodem状态机</td></tr><tr><td>key</td><td>13</td><td>5ms</td><td>20ms</td><td>读GPIO，检测下降沿，发MQ通知LVGL和idle</td></tr></table><p><strong>为什么LVGL最高优？</strong>智能手表和人交互的唯一界面就是屏幕——画面卡顿立刻可感知。LVGL每5ms需要跑一次帧渲染，sensor的I2C忙等（约5-10ms）如果优先级比LVGL高，会挡住渲染导致画面跳帧。LVGL在优先级7意味着不管sensor在做什么——调度器会立刻把CPU抢过来交给LVGL。sensor数据晚20ms更新用户完全感受不到，LVGL晚5ms刷新立刻看到顿一下。这是"用户体验优先于后台数据时效"的原则。</p><p>LVGL时间片15ms而非默认5ms——优先级7上没有同级竞争者，时间片轮转只在同优先级间触发。15ms是防御值——万一将来有同级线程，至少能完整渲染一帧再让出CPU。</p>` },
      { id: "ri-21", tags: ["架构","线程"], q: "[项目] 为什么sensor优先级11？idle为什么是9？", a: `<p><strong>sensor优先级11：</strong>I2C用os_udelay忙等读FIFO——一次约5-10ms。如果sensor优先级高于LVGL，每次I2C期间LVGL的5ms定时到了也无法渲染。sensor降到11后LVGL(7)/idle(9)/stop(10)都可随时抢占它。传感器数据晚几十ms对功能无影响——UI下一次500ms刷新时自然拿到最新值。</p><p><strong>idle优先级9：</strong>高于sensor(11)——保证idle线程就绪时不被sensor的I2C阻塞。最坏情况被LVGL挡住：LVGL正在执行一帧lv_timer_handler，idle需等LVGL主动让出CPU（最多5ms）。5ms的亮度恢复延迟人眼完全感知不到（视觉反应时间约100-200ms）。所以idle不需要和LVGL同级——9就够了。</p><p><strong>sensor基准周期从500ms改为50ms：</strong>用单一uint8_t计数器取模分频——tick%2→IMU每100ms、tick%10→心率血氧每500ms、tick%40→温湿度每2s。单计数器方案比原来三个独立静态计数器的好处是所有传感器基于同一时间基准，不存在各计数器因不同复位周期导致的相位漂移。</p>` },

      // ========== 个人项目 - 健康算法 ==========
      { id: "ri-22", tags: ["算法","心率","PPG","高频"], q: "[项目] 从手指放上传感器到显示心率血氧，完整处理链路是怎样的？", a: `<p><strong>先理解三个概念：</strong></p><ul><li><strong>PPG：</strong>MAX30102的红光和红外LED交替发光照进手指，心脏每跳一次血管血容量增加→光被多吸收一点→反射光减少→传感器数值出现微小下降。这个随心跳波动的光强信号就是光电容积脉搏波</li><li><strong>DC（直流分量）：</strong>皮肤/骨骼/肌肉对光的固定衰减，数值很大（约十万量级），不随脉搏变化</li><li><strong>AC（交流分量）：</strong>随脉搏波动的部分——幅度很小，只有DC的约1/50到1/100。AC才是携带心率和血氧信息的核心</li></ul><p><strong>第一步——硬件自动采样：</strong>MAX30102以100sps自动工作，每周期10ms红光LED亮411μs+红外LED亮411μs采样，各出18位值成对存入32槽FIFO。每500ms驱动轮询一次读出最多8对。</p><p><strong>第二步——一阶IIR去直流：</strong>baseline = baseline + 0.01×(raw - baseline)。α=0.01、截止频率约0.16Hz，刚好低于最低心率0.5Hz。AC = |raw - baseline|。红光和红外各独立做一遍。</p><p><strong>第三步——心率计算：</strong>七点滑动窗口扫描去直流后的红光AC——中心点≥其余六个点认定为心跳峰值。两次峰间隔<425ms的丢弃（>141bpm噪声）。连续收集7个瞬时心率取算术平均。动态阈值=窗口均值+(极差÷4)，自动适应不同用户信号强弱。</p><p><strong>第四步——血氧计算：</strong>两路AC各维护32点滑动窗口。DC=窗口均值，AC=窗口峰峰值。R=(红光AC/红光DC)÷(红外AC/红外DC)——先各自除以DC做归一化（排除手指粗细肤色影响），再相除约掉DC绝对值，R值只反映血红蛋白的化学特性。SpO2=110-25×R，钳位70%~100%。</p>` },
      { id: "ri-23", tags: ["算法","DSP","高频"], q: "[项目] IIR的α为什么取0.01？窗口为什么是七点？±3bpm怎么验证的？", a: `<p><strong>α=0.01</strong>在100sps下截止约0.16Hz——刚好低于0.5Hz最低心率，保留完整脉搏波动。α取0.1则截止1.6Hz→脉搏信号会被当DC吃掉。α取0.001太慢→姿势变化导致基线抬升要几十秒才能跟上，这期间血氧值不准。</p><p><strong>七点窗：</strong>跨70ms，刚好捕获一个心跳收缩峰（宽约100-200ms）的完整上升下降沿。三点太窄易被噪声触发，七点在抗噪和灵敏度间平衡最好。</p><p><strong>验证方法：</strong>Polar H10胸带做对照——五人静坐加步行各三分钟，每整分钟对比手表输出和Polar值，共30组数据。静坐±2bpm，步行±3bpm。运动伪影用MPU6050加速度辅助——三轴合成超1.5g标记数据不可靠不参与计算。</p>` },
      { id: "ri-24", tags: ["算法","血氧"], q: "[项目] 为什么心率只要AC、血氧需要AC和DC两个？区别在哪？", a: `<p><strong>心率看"什么时候跳"</strong>——AC峰值在时间轴上的位置，DC不影响峰出现的时刻。只需AC信号做峰检测即可。</p><p><strong>血氧看"跳的幅度比例"</strong>——不同人的皮肤吸收差异导致AC绝对值差距巨大（皮肤厚的AC可能只有皮肤薄的1/3），直接比绝对值不准确。必须先除以各自的DC做归一化，把AC变成和手指物理条件无关的比例值，再跨通道比较。此时DC被约掉，R值只反映血红蛋白的化学特性。这是PPG血氧计算最核心的原理。</p>` },

      // ========== 个人项目 - OTA升级 ==========
      { id: "ri-25", tags: ["OTA","Bootloader","高频"], q: "[项目] Flash分区怎么划分的？从PC端SecureCRT到手表重启的完整OTA流程？", a: `<p><strong>Flash分区（GD32F405 1MB）：</strong></p><pre><code>0x08000000 ┌──────────────────┐
           │   Bootloader     │  16KB （上电启动）
0x08004000 ├──────────────────┤
           │   APP_A          │  496KB（当前运行固件）
0x08080000 ├──────────────────┤
           │   APP_B          │  496KB（OTA目标分区）
0x080FC000 ├──────────────────┤
           │   Reserved       │  16KB
0x080FFFFF └──────────────────┘</code></pre><p><strong>阶段一——进入OTA：</strong>手表收到OV+OTA命令→EEPROM写UPDATE_STATUS=0x01（传输中）→回复+OTA_READY→每秒发'C'（请求CRC16校验模式的Ymodem传输）。</p><p><strong>阶段二——Ymodem握手+传输：</strong>SecureCRT Send Ymodem选.bin文件→发第0包（SOH+128字节）含文件名和大小→解析后擦除APP_B区→回ACK再发'C'→从1号包起每包1024字节+2字节CRC16-CCITT→STM32独立算CRC→通过回ACK写入Flash，失败回NAK触发SecureCRT重发→全部发完后EOT握手（两次）+空包确认传输完毕。</p><p><strong>阶段三——写标志位+复位：</strong>EEPROM写BOOT_TARGET=0x01（下次启动APP_B）+ UPDATE_STATUS=0xFF（完成）→NVIC_SystemReset()软件复位。Bootloader上电读EEPROM BOOT_TARGET→0x00跳APP_A、0x01跳APP_B→关全局中断→设MSP/PC→跳转。</p><p><strong>阶段四——看门狗回滚：</strong>APP_B启动后5秒内没喂够IWDG→看门狗复位→Bootloader检测复位源为IWDG而非POR→读BOOT_COUNT→连续失败≥3次强制改BOOT_TARGET回0x00跳APP_A。</p>` },
      { id: "ri-26", tags: ["OTA","CRC","校验","高频"], q: "[项目] CRC校验怎么保证数据传输不出错？每包的具体过程？三层校验机制？", a: `<p><strong>第一层——BLE链路层CRC：</strong>KT6368 BLE无线传输自带链路层24位CRC，每个空中包都带校验值，接收端硬件自动校验。校验失败自动丢弃并请求重传。硬件实现，不占CPU。只能保证"BLE空中这一段"正确。</p><p><strong>第二层——Ymodem协议层CRC16-CCITT（应用层端到端校验）：</strong>参数：多项式0x1021，初值0x0000，输入输出均不反转。每收到一包的1024字节后，STM32在RAM里独立计算一次CRC16，和SecureCRT发来附在包尾的2字节CRC16比对——匹配→回ACK(0x06)→按字写入Flash；不匹配→回NAK(0x15)→SecureCRT自动重发本包。CRC16能检出所有奇数个比特翻转、所有长度≤16的突发错误、99.998%长度>17的突发错误。每包独立校验——错误只重发一包而非整个256KB文件重传。</p><p><strong>第三层——EEPROM标志位兜底（防Flash写入途中断电）：</strong>EEPROM的UPDATE_STATUS在OTA开始前先写0x01（传输中），全部包写完且EOT确认后才写0xFF（完成）。如果传输中途断电——上电后Bootloader读STATUS=0x01就知道APP_B存的是半截固件→直接判定不可用→擦除APP_B→回APP_A。先写状态后写数据——和Linux文件系统journal同样思想。</p>` },
      { id: "ri-27", tags: ["OTA","EEPROM"], q: "[项目] EEPROM存哪些标志位？每个字节的含义？", a: `<table><tr><th>地址</th><th>名称</th><th>字节</th><th>含义</th></tr><tr><td>0x10</td><td>BOOT_TARGET</td><td>1</td><td>0x00=APP_A, 0x01=APP_B</td></tr><tr><td>0x11</td><td>UPDATE_STATUS</td><td>1</td><td>0x00=空闲, 0x01=传输中, 0xFF=完成</td></tr><tr><td>0x12</td><td>DEFAULT_BANK</td><td>1</td><td>当前稳定版是A还是B</td></tr><tr><td>0x13</td><td>BOOT_COUNT</td><td>1</td><td>连续启动失败计数，≥3回滚</td></tr><tr><td>0x14</td><td>IMAGE_SIZE</td><td>4</td><td>当前固件大小，小端序</td></tr></table><p>UPDATE_STATUS是整个掉电保护的核心——固件写到一半断电，下次上电Bootloader看到STATUS=0x01就知道APP_B是坏的，清空标志跳APP_A。</p>` },

      // ========== 个人项目 - 电源管理 ==========
      { id: "ri-28", tags: ["功耗","休眠","高频"], q: "[项目] 四级电源状态机怎么切换？休眠功耗<1mA怎么测？", a: `<p><strong>四级状态：</strong></p><ol><li><strong>正常：</strong>全外设开，LVGL正常亮度，MAX30102连续采样，BLE保持连接</li><li><strong>息屏（30s无操作）：</strong>背光降到5%，传感器和BLE保持</li><li><strong>休眠（再300s无操作）：</strong>enter_sleep回调依次关传感器→BLE→LCD+触摸→看门狗→MCU进STOP模式，只留RTC和按键/充电外部中断</li><li><strong>充电：</strong>检测引脚拉低→邮箱发WAKEUP_CHARGE→idle线程切换充电态禁休眠</li></ol><p>唤醒后exit_sleep反序恢复——先开看门狗、再LCD和触摸、最后BLE和传感器。顺序重要：SPI和DMA的时钟在STOP模式下停了，必须重新初始化才能恢复LCD显示。</p><p><strong>功耗测量：</strong>万用表串电池正极和VCC，mA档。正常约30mA，STOP模式实测约0.8mA（手册STOP约0.4mA+LSE 0.2mA+GPIO漏电0.2mA）。500mAh电池纯待机625h≈26天。正常使用每天亮屏2h+休眠22h≈82mAh，充一次约6天。</p>` },
      { id: "ri-29", tags: ["功耗","IPC","邮箱"], q: "[项目] 为什么唤醒通知用邮箱不用消息队列？四个唤醒源怎么区分？", a: `<p><strong>MQ每条消息1字节——</strong>四种唤醒源发的都是同一个uint8_t(1)，idle线程收到后完全不知道是谁唤醒的，只能无差别恢复。但充电唤醒和按键唤醒的处理策略应该不同——充电要进充电态禁休眠，按键的可能需要继续处理按键事件。</p><p><strong>改用邮箱：</strong>每消息4字节，定义wakeup_source_t枚举——WAKEUP_KEY=1、WAKEUP_TOUCH=2、WAKEUP_CHARGE=3、WAKEUP_WRIST=4。idle线程switch-case做差异化处理：充电直接进充电态、触摸不触发UI点击避免误触、按键可跳特定页面。MQ和邮箱在RT-Thread中底层实现非常接近——都是基于链表管理IPC消息——不存在性能差异。邮箱的设计定位是"允许传递4字节值而非复制固定大小缓冲区"，正适合需要区分来源的通知场景。</p>` },

      // ========== 个人项目 - GUI优化 ==========
      { id: "ri-30", tags: ["GUI","LVGL","性能","高频"], q: "[项目] 页面栈怎么做到15页降到2页（87%内存）？SPI DMA怎么提帧率（40%）？", a: `<p><strong>87%内存节省：</strong>GUI Guider生成15个screen全部编译期创建，控件对象挤满SRAM。改静态页面栈——Push时创建screen，Pop时lv_obj_del递归释放子控件。任何时刻只保留栈顶和上一页共2个screen，控件内存降约87%。</p><p><strong>40%帧率提升（12→20fps）：</strong>LVGL双缓冲Partial Render——分配两个15行高的缓冲区。LVGL在Buffer1渲染当前条带时，DMA在后台把Buffer2上一条带的像素发到LCD。逐像素全屏约85ms（12fps）→ DMA流水线约50ms（20fps），提升约40%。DMA把SPI传输从CPU阻塞等待变为DMA后台搬运，CPU可以并行做渲染计算。</p>` },

      // ========== 个人项目 - 遇到的问题 ==========
      { id: "ri-31", tags: ["调试","IPC","高频"], q: "[项目] 在项目中遇到过什么问题？具体怎么解决的？（唤醒通知+传感器周期+优先级卡顿）", a: `<p><strong>问题一——唤醒通知用MQ分不清唤醒源：</strong>息屏模式下按键/触摸/充电/抬腕四种操作都能唤醒手表，MQ每条消息只传1字节——四种源发的都是同一个1，idle线程收后不知道是谁唤醒的。改用RT-Thread邮箱替代MQ——每消息4字节传枚举值（KEY=1/TOUCH=2/CHARGE=3/WRIST=4），idle线程switch-case做差异化处理。</p><p><strong>问题二——传感器轮询周期和注释不一致，实际读IMU频率比预期慢十倍：</strong>基准延时500ms→IMU条件++imu_tick>=2→2×500ms=1秒才读一次，注释标的却是"每100ms"——差了十倍。另外AHT20每2秒触发80ms转换等待（os_thread_delay_ms阻塞），排在后面的传感器数据晚80ms才更新。解决：基准延时降为50ms→废弃三个独立静态计数器→改为单一计数器取模分频（tick%2→IMU 100ms/tick%10→心率500ms/tick%40→温湿度2s），所有传感器基于同一时间基准。</p><p><strong>问题三——LVGL被传感器I2C抢占导致画面卡顿：</strong>原来传感器优先级高于LVGL→每次I2C忙等时LVGL定时到了也无法渲染→画面每0.5秒卡一次。解决：LVGL提最高优(7)、sensor降低优(11)。LVGL苏醒时不管sensor在做什么立刻抢占CPU。sensor数据晚十几ms更新功能无影响——UI下一次500ms刷新时自然拿到最新值。</p>` },

      // ========== 面试官追问 ==========
      { id: "ri-32", tags: ["追问","I2C","GPIO"], q: "[追问] 软件I2C怎么实现的？为什么不用硬件I2C？", a: `<p><strong>实现：</strong>用GPIO开漏输出+os_udelay微秒延时模拟时序。起始条件先拉低SDA再拉低SCL，停止条件先释放SCL再释放SDA。发送字节从高位起逐位输出、每拉低SCL后延时再拉高形成时钟脉冲，第9位释放SDA读ACK。</p><p><strong>为什么不用硬件I2C：</strong>STM32F4的硬件I2C有已知Bug——Slave拉低SCL导致总线死锁后不会自动恢复，整个I2C总线挂死。软件I2C移植性好——换MCU只改GPIO和延时，不用重新配寄存器。缺点：os_udelay忙等期间不关中断→被抢占时位时序可能被打断（传感器线程优先级已降到11，对I2C影响是插入额外延迟而非翻转位值，通信不会出错）。</p>` },
      { id: "ri-33", tags: ["追问","DMA","ADC"], q: "[追问] DMA乒乓缓冲怎么工作的？为什么比单缓冲好？", a: `<p><strong>实现：</strong>分配64半字连续缓冲区——前32半字Buffer0、后32半字Buffer1。ADC通过DMA循环模式持续往这填采样值。DMA填满前32半字触发半满中断→CPU立刻处理Buffer0的数据（算均值/转电压）。DMA继续往后32半字填数据，完全不受CPU处理Buffer0的影响。填满Buffer1触发全满中断→CPU处理Buffer1。如此循环。</p><p>单缓冲：ADC采样完一批→CPU处理→CPU处理完再启动下一批。CPU处理期间ADC停等。乒乓缓冲下DMA永远在采样，CPU永远在处理已完成半区，两不阻塞。CPU只在半满和全满两个中断各做一次32点均值运算，其余时间完全释放。</p>` },
      { id: "ri-34", tags: ["追问","迁移","GD32"], q: "[追问] GD32F405和STM32F411的代码迁移需要改哪些？", a: `<p>只需改系统抽象层的<strong>8个</strong>hal_*_stm32.c文件和1个board_watch1.h引脚定义文件。每个_stm32.c改成_gd32.c，里面调GD32固件库替代STM32 HAL——gpio_init()替代HAL_GPIO_Init()、spi_init()替代HAL_SPI_Init()。外设寄存器基地址一样（ARM Cortex-M标准映射0x40000000），只是库函数名和参数枚举值不同。board_watch1.h改引脚定义宏——PA1还是PA1。</p><p>上层drivers、services、app三个目录共<strong>50+文件零改动</strong>。换芯片工作量约2-3天。约80%代码直接复用。</p>` },
      { id: "ri-35", tags: ["追问","SRAM","栈"], q: "[追问] SRAM够用吗？线程栈大小怎么定的？为什么选RT-Thread？", a: `<p><strong>SRAM使用：</strong>LVGL帧缓冲双缓冲每块240×15×2+内部对象管理≈22KB、六个线程栈（LVGL 7KB+sensor 1KB+ble 1KB+idle 256B+stop 512B+key 256B）≈10KB、内核≈4KB、总计≈36-40KB。GD32F405有192KB SRAM，剩150KB+余量。</p><p><strong>栈大小确定：</strong>编译时启用RT_USING_OVERFLOW_CHECKER→运行时list_thread看max used百分比→留30%余量作为最终值。</p><p><strong>为什么选RT-Thread而非FreeRTOS：</strong>RT-Thread组件生态更完整——设备框架/文件系统/网络协议栈/finsh Shell命令行内核自带。finsh调试阶段极有价值——串口终端敲list_thread看栈使用率、free看内存分布。而且我用OSAL封装了RT-Thread API——将来换FreeRTOS只改OSAL层5个.c文件，上层代码不动。</p>` },
      { id: "ri-36", tags: ["追问","软硬件"], q: "[追问] 在这个项目中你既是嵌入式开发又涉及硬件选型，软硬件边界怎么划分？", a: `<p>硬件侧我做的是外设选型（MAX30102/MPU6050/ST7789/KT6368/AHT20）和原理图评审——确认I2C地址不冲突、SPI片选独立、中断引脚够用。软件侧我负责全部固件——从启动代码到LVGL UI到BLE协议栈到OTA。</p><p><strong>软硬件协作的典型场景：</strong>比如MAX30102的INT引脚——硬件上拉到MCU的GPIO，软件配置为下降沿中断。调试时发现中断偶尔不触发→示波器量INT引脚→发现是OD输出+上拉电阻偏大导致上升沿太慢→加小电阻解决。这个问题本质上是软硬件边界不清晰——硬件觉得"拉个电阻就行"，软件觉得"中断应该能触发"，实际是信号完整性卡在中间。现在我评审原理图时会专门关注开漏引脚的上升时间。</p>` }
      // ========== 技术深度问答 ==========
      { id: "ri-30", tags: ["RT-Thread","任务切换","进阶"], q: "RT-Thread中任务切换的完整流程是怎样的？从SysTick到PendSV讲一下", a: `<p><strong>完整链路：</strong>SysTick中断→<code>rt_os_tick_callback</code>→更新全局tick→递减当前线程剩余时间片。若时间片归零→<code>rt_thread_yield()</code>→<code>rt_schedule()</code>选最高优先级就绪线程→<code>rt_hw_context_switch()</code>悬起PendSV。SysTick退出后，PendSV_Handler执行真正上下文切换：保存当前线程R4-R11→恢复下一个线程寄存器→完成切换。</p><p><strong>软定时器触发高优先级任务抢占的情况：</strong><code>rt_timer_check()</code>在同一个SysTick_Handler中执行超时回调（如<code>rt_sem_release</code>唤醒高优先级线程）。该线程进入就绪态后，即使当前线程时间片未用完，调度器通过全局优先级位图检测到更高优先级就绪线程→<code>rt_schedule()</code>主动触发PendSV→立即抢占。</p><p><strong>关键设计：</strong>利用Cortex-M的PendSV（优先级最低）实现上下文切换——确保在所有ISR处理完毕后才做切换，不打断正在执行的ISR。</p>` },
      { id: "ri-31", tags: ["RT-Thread","FreeRTOS","对比"], q: "RT-Thread相比FreeRTOS多了哪些组件？", a: `<ul><li><strong>设备框架(rt_device)</strong>：统一设备操作接口（rt_device_find/read/write），方便驱动复用，类似Linux设备模型</li><li><strong>Finsh Shell控制台</strong>：交互式命令行，支持查看线程/内存/设备、执行函数，嵌入式调试利器</li><li><strong>虚拟文件系统(DFS)</strong>：支持FAT/LittleFS/NFS等，统一VFS接口</li><li><strong>SAL套接字抽象层</strong>：屏蔽底层网络协议栈差异（lwIP/AT Socket），应用层无感知切换</li><li><strong>软件包生态</strong>：400+第三方package可通过menuconfig一键集成（LVGL/AT指令/MQTT/HTTP等）</li><li><strong>传感器框架</strong>：已支持100+传感器驱动</li></ul><p>FreeRTOS只提供核心调度+IPC，其余需自行集成。RT-Thread是一个完整的IoT OS平台。</p>` },
      { id: "ri-32", tags: ["Linux","驱动","对比"], q: "Linux驱动开发和STM32裸机/RTOS驱动开发最大的区别是什么？", a: `<p><strong>三大核心区别：</strong></p><ol><li><strong>架构不同</strong>：Linux有统一的设备模型（platform_device/driver），驱动必须遵循框架规范（probe/remove/fops）；STM32驱动自由度高，直接操作寄存器即可</li><li><strong>内存管理不同</strong>：Linux有虚拟内存，驱动运行在内核态，不能直接访问物理地址，必须先ioremap成虚拟地址；STM32是物理内存，直接访问寄存器地址</li><li><strong>并发控制不同</strong>：Linux是多用户多任务系统，驱动需考虑多进程同时访问（用spinlock/mutex保护）；RTOS虽有多任务但没有进程概念，共享内存空间中并发控制相对简单</li></ol><p>Linux驱动开发门槛更高——需要理解内核框架、设备模型、并发保护、内核内存管理等。但一旦掌握了框架，写驱动是有章可循的；STM32驱动更自由但也更容易写出不规范代码。</p>` },
      { id: "ri-33", tags: ["Bootloader","跳转"], q: "Bootloader中跳转到应用程序的具体步骤是什么？", a: `<pre><code class="language-c">#define APP_ADDR 0x08008000

void jump_to_app(void) {
    // 1. 检查APP是否存在（读EEPROM标志或APP起始地址内容）
    if (*(uint32_t*)APP_ADDR == 0xFFFFFFFF) return; // APP不存在

    // 2. 关闭SysTick和全局中断
    SysTick->CTRL = 0;
    __disable_irq();

    // 3. 重定向向量表
    SCB->VTOR = APP_ADDR;

    // 4. 设置MSP为APP的栈顶地址
    __set_MSP(*(uint32_t*)APP_ADDR);

    // 5. 获取APP复位向量并跳转
    void (*app_reset_handler)(void) = (void (*)(void))*(uint32_t*)(APP_ADDR + 4);
    app_reset_handler();  // 永不返回
}</code></pre><p><strong>关键点：</strong>关SysTick（防止跳转过程中产生中断）、关全局中断、设置VTOR（APP使用自己的向量表）、设置MSP（APP的栈指针从APP固件头读出）、函数指针跳转。</p>` },
      { id: "ri-34", tags: ["设备树","Linux"], q: "设备树在哪一步加载？作用是什么？为什么需要设备树？", a: `<p><strong>加载时机：</strong>设备树（DTB）由U-Boot加载（从eMMC/SD/NAND读到内存指定地址）→启动内核时通过寄存器R2传递DTB地址→内核在<code>start_kernel</code>之前的<code>setup_machine_fdt</code>中解析设备树，建立设备模型。</p><p><strong>作用：</strong>以结构化方式描述板级硬件信息（寄存器地址、中断号、时钟、GPIO、总线拓扑）。</p><p><strong>为什么需要：</strong>在设备树之前，ARM平台每个板子要写board-xxx.c板级文件，硬件变一点就要改内核代码重新编译。引入设备树后：(1)硬件信息与内核代码解耦 (2)同一个zImage+不同dtb适配多个硬件平台 (3)驱动不再写死地址/中断号 (4)改硬件只需改dts，无需重新编译内核。</p>` },
      { id: "ri-35", tags: ["Linux","IPC"], q: "Linux进程间通信(IPC)方式及使用场景？", a: `<table><tr><th>方式</th><th>特点</th><th>使用场景</th></tr><tr><td>匿名管道</td><td>半双工、仅父子进程</td><td>popen()读取命令输出</td></tr><tr><td>有名管道(FIFO)</td><td>无亲缘进程可通信</td><td>模拟传感器数据源</td></tr><tr><td>消息队列</td><td>消息边界清晰、有序传递</td><td>小块结构化数据传递</td></tr><tr><td>共享内存</td><td>最快速（零拷贝）</td><td>视频帧传递（配合信号量同步）</td></tr><tr><td>信号</td><td>异步通知、信息量少</td><td>SIGIO异步I/O事件</td></tr><tr><td>Socket</td><td>跨网络/本地通信</td><td>本机进程间(Unix domain)或网络</td></tr></table>` },
      { id: "ri-36", tags: ["协议","SPI","I2C","对比"], q: "SPI和I2C在总线协议上的区别？什么场景选哪个？", a: `<table><tr><th>特性</th><th>SPI</th><th>I2C</th></tr><tr><td>信号线</td><td>4根(MOSI/MISO/SCLK/CS)</td><td>2根(SDA/SCL)</td></tr><tr><td>时钟与应答</td><td>主机产生时钟，无应答</td><td>主机产生时钟，每字节后有ACK/NACK</td></tr><tr><td>多主仲裁</td><td>不支持，通过CS区分从机</td><td>支持，通过SDA线与仲裁（低电平优先）</td></tr><tr><td>速率</td><td>可达几十MHz</td><td>100k/400k/1MHz</td></tr><tr><td>全/半双工</td><td>全双工</td><td>半双工</td></tr></table><p><strong>选型经验（项目实践）：</strong>心率传感器EM7028用I2C（引脚少、400kbps足够），LCD屏幕用SPI（需要高刷新率、MHz级传输）。规则：高速大量数据→SPI；引脚紧张→I2C。</p>` },
      { id: "ri-37", tags: ["调试","面试技巧"], q: "全局变量的值与预期不一样，怎么排查？", a: `<ol><li><strong>定位所有写入点</strong>：查看源码中哪些位置修改该变量，检查是否有不该写的地方在写</li><li><strong>检查越界覆盖</strong>：在变量前后放置哨兵字节（Magic Number），若哨兵被修改说明是越界覆盖</li><li><strong>数据断点（Watchpoint）</strong>：调试器中设硬件断点，该地址被写入时自动中断，查看调用栈——最快的方法</li><li><strong>并发修改</strong>：若被中断和主循环同时访问，临时加临界区验证是否竞态条件引起</li><li><strong>volatile检查</strong>：若变量在中断中修改，确认声明为volatile，否则编译器可能用寄存器缓存旧值</li><li><strong>编译器优化</strong>：降低优化级别（-O0），看问题是否消失，确认是否与优化相关</li></ol>` },
      { id: "ri-38", tags: ["C语言","内存对齐"], q: "怎么防止结构体内存对齐？什么时候需要紧凑排列？", a: `<p><strong>方法：</strong>用<code>#pragma pack(1)</code>或<code>__attribute__((packed))</code>。</p><pre><code class="language-c">struct __attribute__((packed)) packed_struct {
    char a;    // 1 byte
    int b;     // 4 bytes（本来有3 byte padding）
    short c;   // 2 bytes
}; // 总大小7字节而不是12字节</code></pre><p><strong>需要紧凑排列的场景：</strong></p><ul><li>通信协议帧解析（帧格式按字节紧密排列，padding会破坏解析）</li><li>硬件寄存器映射（寄存器布局由硬件固定）</li><li>Flash/EEPROM中存储结构体（节省空间+读写一致性）</li></ul><p><strong>代价：</strong>非对齐访问在某些架构上可能触发HardFault（Cortex-M0），或效率降低（需要多次字节组合）。只在必要时使用。</p>` },
      { id: "ri-39", tags: ["RTOS","实时性"], q: "线程时间片设为5ms，实时性高吗？", a: `<p>5ms时间片不算高实时，属于<strong>常规配置</strong>。RT-Thread是<strong>抢占式内核</strong>，高优先级任务可以<strong>立即抢占</strong>低优先级任务——实时性由调度机制（抢占+优先级）决定，不是由时间片决定。时间片只影响同优先级任务间的轮转频率。</p><p>5ms可满足一般嵌入式场景（如穿戴设备的心率检测/UI刷新）。工业/汽车级高实时场景（如电机FOC控制/ABS制动）需要：</p><ul><li>更短时间片（1ms或更小）</li><li>更高的tick频率（如10kHz）</li><li>甚至不用tick调度而用硬件定时器直接触发最高优先级任务</li></ul>` },

      // ========== 开放性问题 ==========
      { id: "ri-40", tags: ["HR","面试技巧"], q: "[面试官常问] 如何看待AI？日常会使用AI工具吗？", a: `<p>我认为AI（特别是大语言模型）已经成为软件开发中<strong>非常高效的辅助工具</strong>。它不能替代工程师对系统底层原理的理解和调试能力，但可以极大提升学习和生产效率。</p><p><strong>我的实际使用方式：</strong></p><ol><li><strong>快速理解新协议/芯片手册</strong>：看EM7028传感器手册时，让AI帮忙总结寄存器配置流程，然后我再对照手册仔细验证——相当于一个能快速定位关键信息的"智能助手"</li><li><strong>代码Review辅助</strong>：把核心代码片段让AI检查潜在边界问题，但不盲从——AI给的建议我会逐条分析合理性</li><li><strong>面试准备</strong>：让AI基于我的项目模拟面试官追问，发现回答中的薄弱点</li></ol><p><strong>底线：</strong>所有AI输出都要经过自己的理解验证。不理解原理的代码绝对不能直接使用。AI是工具，人做决策。</p>` },
      { id: "ri-41", tags: ["项目","难点","面试技巧","高频"], q: "[面试官常问] 你这个项目最大的技术难点是什么？怎么解决的？", a: `<p><strong>最大的难点不是某个具体Bug，而是架构决策。</strong></p><p><strong>决策一：IPC边界问题。</strong>一开始想在层间全用消息队列做异步解耦，画完时序图发现一次传感器读取需要4次上下文切换，延迟高到不可接受。查阅PX4飞控和ESP-IDF源码后确认业界标准是"垂直直接调用+水平消息队列"，纠正了设计。</p><p><strong>决策二：设备管理过度设计。</strong>最初想引入Linux platform bus做设备注册/匹配/probe，写完伪代码后发现项目只有10个外设且编译期全部已知，probe/match的代码量远超实际价值。最终用全局数组+名称查找替代，代码从300+行缩减到60行。</p><p><strong>核心收获：</strong>架构不是越复杂越好，适合项目规模的才是好架构。这两个决策让我在"解耦"和"简单"之间找到了平衡点。</p>` },
      { id: "ri-42", tags: ["RTOS","调试"], q: "[项目] 高优先级任务占着CPU导致低优先级任务饿死，你怎么解决？", a: `<p><strong>遇到过。</strong>项目初期心率算法任务优先级设为3（较高），计算耗时约50ms，导致GUI更新任务（优先级6）长时间得不到运行，界面卡顿。</p><p><strong>解决方案：</strong></p><ol><li><strong>让出CPU</strong>：心率任务在完成一次计算后主动<code>rt_thread_delay(10)</code>挂起10ms，给GUI任务执行窗口——这是最简单的方案</li><li><strong>降低计算频率</strong>：分析发现没必要每次心跳都更新显示，改为每5次计算刷新一次GUI</li><li><strong>计算分段</strong>：把50ms的算法拆成多个小段，每段执行完主动yield，避免长时间霸占CPU</li></ol><p>根本原则：高优先级任务不能长时间占用CPU。必须给低优先级任务留出执行窗口（通过delay/yield或提高tick频率）。</p>` },
      { id: "ri-43", tags: ["调试","FIFO","传感器"], q: "[项目] EM7028心率传感器数据突然归零的问题怎么排查和解决的？", a: `<p><strong>现象：</strong>设备运行几分钟后心率数据突然归零，重启后恢复。</p><p><strong>排查过程：</strong></p><ol><li>示波器抓I2C总线波形→确认数据传输仍在进行，传感器没死</li><li>读数据手册→发现传感器默认采样率<strong>100Hz</strong>，内部FIFO大小有限（32 samples）</li><li>分析代码→读取周期设的是<strong>100ms（10Hz）</strong>——远低于传感器输出速率（100Hz）</li><li>RT-Thread任务调度导致实际读取间隔不稳定→传感器每秒产生100个样本但代码每秒只取10个→FIFO在约0.3秒内溢出→后续数据全部丢失→归零</li></ol><p><strong>解决：</strong>配置传感器采样率降到10Hz匹配读取周期、增加连续读失败3次则软复位传感器的恢复逻辑。此后数据稳定。</p>` },
      { id: "ri-44", tags: ["OTA","AB分区"], q: "[追问] 汽车OTA升级AB分区机制如何保证安全？", a: `<p>AB分区机制：Flash分为A区（当前运行固件）和B区（升级目标固件）。</p><p><strong>安全保障机制：</strong></p><ol><li><strong>写入阶段</strong>：固件分块写入B区，每块<strong>CRC32校验</strong>→全部写入后验证<strong>ECDSA数字签名</strong>→防传输错误和固件篡改</li><li><strong>切换阶段</strong>：设置升级标志位→重启→Bootloader检测标志→验证B区固件完整性（<strong>SHA256+签名</strong>）→验证通过才切换活动分区</li><li><strong>回滚机制</strong>：B区启动后执行健康检查（心跳正常+通信OK+功能自测）→通过则<strong>提交</strong>固件（commit→A区成为下次升级备区）→失败则**自动回滚A区**</li></ol><p><strong>防变砖的核心：</strong>Bootloader独立不可升级。无论固件怎么坏，Bootloader始终完好，能读取AB分区标志并选择正确（或上一个完好）的固件启动。</p>` },
      { id: "ri-45", tags: ["运动补偿","算法","进阶"], q: "[追问] PPG心率算法如果有运动干扰怎么办？", a: `<p><strong>当前版本没有做运动补偿，这是算法的一个局限。</strong></p><p><strong>运动伪影来源：</strong>手腕晃动→传感器和皮肤距离变化→DC基线漂移；肌肉收缩→血液灌注变化→AC信号被调制。</p><p><strong>改进方向（两个方案）：</strong></p><ol><li><strong>自适应噪声门控</strong>：利用MPU6050三轴加速度合成值——超过阈值说明用户在运动→标记这段PPG数据为不可靠→不参与心率计算。简单有效但会丢失运动期间的心率数据</li><li><strong>LMS自适应滤波</strong>：把加速度信号作为噪声参考输入→自适应滤波器从PPG信号中减去运动相关分量。能恢复运动期间的心率，但算法复杂度高、需要调参</li></ol><p>这两个方案的核心思路文献中都有（TROIKA、JOSS等），但当前项目版本还没实现。如果在面试中被追问到这个，坦诚说明局限+提出改进方向比假装完美更有说服力。</p>` },
      { id: "ri-46", tags: ["CI","自动化测试"], q: "[追问] 测试用例集成到CI流程中，是怎么实现的？", a: `<p><strong>流程：</strong>开发者提交代码→CI Jenkins Pipeline触发→自动编译→烧录目标板→运行STL测试套件→采集结果→生成报告。</p><p>STL的GTC测试用例作为测试套件的一部分，每次代码变更后自动在目标硬件上运行。如果GTC测出时间偏差超限→测试失败→CI发邮件通知提交者→代码需修复后才能合入。</p><p>此外，Tessy单元测试也在CI中有独立Pipeline，运行在PC模拟环境（不依赖硬件），检查代码覆盖率是否达标（>85%）。这种<strong>软硬结合的双层测试</strong>同时保证了代码逻辑正确性和硬件行为正确性。</p>` }
    ]
  }
];

// EMBEDDED_DATA 定义已移至 data_supplement.js 末尾
