const DATA_RESUME = [
  {
    id: "resume-interview",
    name: "简历面试与项目深挖",
    icon: "📋",
    questions: [
      // ========== 海康威视实习 - GTC平台化 ==========
      { id: "ri-1", tags: ["海康","平台化","高频"], q: "[海康] GTC模块平台化的核心思想是什么？解决了什么问题？", a: `<p>核心思想：通过<strong>编译时条件隔离 + 运行时动态适配</strong>，让同一份GTC时间戳驱动代码支持多款TI SoC（J721E/J721S2/J784S4）和不同CPU核（ARM Cortex-A/C66x DSP/Cortex-R），上层调用<code>hal_gtc_getms()</code>无需关心底层差异。</p><p><strong>三个关键设计：</strong></p><ul><li><strong>多SoC编译隔离</strong>：<code>#if defined(SOC_J721E)</code>包含不同的寄存器基址头文件和CSL库路径，避免错误编译</li><li><strong>地址映射差异抽象</strong>：J721E上C66x DSP核需通过RAT做地址转换，代码中通过<code>hal_get_cpuid()</code>运行时判断CPU核类型，动态设置<code>uG_gtc_base</code></li><li><strong>时钟频率统一</strong>：不同SoC默认时钟可能不同，通过<code>hal_clk_getrate()</code>获取+<code>hal_clk_setrate()</code>统一到200MHz</li></ul><p><strong>效果：</strong>新增芯片只需在初始化增加对应的基址映射逻辑，上层代码零改动。</p>` },
      { id: "ri-2", tags: ["海康","平台化","进阶"], q: "[海康] 在J721E上C66x DSP核不能直接访问GTC寄存器，你是如何解决的？", a: `<p>J721E上C66x DSP核不能直接访问GTC物理地址（0xA90000），必须通过RAT（Region Address Translator）把一段空闲地址空间映射到真实寄存器地址。</p><p><strong>解决方案——运行时动态基址：</strong></p><ol><li>默认基址设为<code>GTC0_GTC_CFG1_BASE</code>（0xA90000）</li><li>编译J721E时通过<code>hal_get_cpuid()</code>获取当前CPU核ID</li><li>如果是C66x_0或C66x_1：先配置RAT映射（把0x200000000映射到0xA90000），再把<code>uG_gtc_base</code>改为0x200000000</li><li>其他核（ARM等）直接用真实地址0xA90000</li><li>J721S2/J784S4无此问题，基址保持0xA90000</li></ol><p>之后所有寄存器读写基于<code>uG_gtc_base</code>，不写死地址、不用<code>#ifdef</code>。同一份代码在所有SoC、所有核上都能正确读到GTC值。</p>` },
      { id: "ri-3", tags: ["海康","平台化","进阶"], q: "[海康] GTC时间同步在主从设备上行为不一致，你是怎么设计的？", a: `<p><strong>问题：</strong>车载场景中主板(Master)是时间源、从板(Slave)需要同步到主板。如果直接在<code>hal_gtc_getus</code>里写<code>return 硬件时间+补偿值</code>，主板不需要补偿但要写时间出去，逻辑耦合混乱。</p><p><strong>解决——分离职责：</strong></p><ul><li><strong>核心函数</strong><code>hal_gtc_getus</code>只做一件事：读取硬件计数÷时钟频率=原始本地时间</li><li><strong>时间同步</strong>通过独立的条件编译块叠加：<code>#if defined(CONFIG_HW_AE_B50038_S) || defined(CONFIG_HW_AE_B50038_M)</code>时额外加<code>CPTS_DIFF_GTC</code>寄存器的补偿值</li><li>从板：差值寄存器已写入主板与本地的时间差，直接加</li><li>主板：差值寄存器为0，或不编入此宏</li><li>主板另有一个独立线程<code>stl_timesync_main</code>负责把自己的GTC时间写入共享内存</li></ul><p>核心时间读取逻辑不受同步逻辑污染，不同硬件形态通过编译宏清晰配置。</p>` },
      { id: "ri-4", tags: ["海康","测试","进阶"], q: "[海康] 平台化后如何验证GTC时间准确性？STL自测框架怎么做的？", a: `<p><strong>仅读寄存器值不够</strong>——你知道计数器在递增，但不知道递增速度对不对。需要端到端功能测试。</p><p><strong>借助STL（Self-Test Library）框架写测试任务：</strong></p><ol><li><code>hal_gtc_getms()</code>获取开始时间→系统<code>sleep(1000)</code>→再获取结束时间→差值应=1000±1ms</li><li>同样测试us接口，同时对比OS tick（sys_pthread_tick）做交叉验证</li><li>us差值应在1,000,000±1000范围，OS tick差值应在1000±1范围</li></ol><p><strong>为什么对比OS tick？</strong>OS tick由另一个独立定时器驱动，两个独立时钟都符合预期→可信度高。如果GTC和OS tick都漂移但方向一致→系统时钟源可能有问题。</p><p><strong>效果：</strong>每个平台移植后跑STL用例自动验证准确性。早期发现过时钟频率获取失败导致的时间漂移，及时修复。测试用例已集成到CI流程。</p>` },
      { id: "ri-5", tags: ["海康","平台化"], q: "[海康] GTC模块使用early_init宏注册，为什么需要早期初始化？", a: `<p><code>early_init(hal_gtc_init);</code>将GTC驱动注册到系统启动早期阶段执行。平台化通用初始化框架定义了模块的初始化顺序，GTC作为时间戳基础设施必须在其他依赖时间的模块（日志、定时器、STL测试框架等）之前完成初始化。</p><p>如果GTC在后期才初始化，依赖它的模块可能在启动时读到未初始化的时钟值（全0或随机值），导致超时判断异常。early_init机制保证启动顺序的确定性。</p>` },

      // ========== 海康威视实习 - Tessy单元测试 ==========
      { id: "ri-6", tags: ["海康","Tessy","测试"], q: "[海康] Tessy单元测试覆盖了哪些模块？发现了什么有价值的Bug？", a: `<p><strong>覆盖模块：</strong>secure（加解密API）、memory（内存分配/释放/地址对齐）、dmaheap（DMA缓冲池分配回收）、network（Socket封装/组播加入离开）、diagnostic（日志输出/assert处理）。</p><p><strong>最有价值的Bug——RSA签名验证中的隐式转换：</strong></p><ul><li>Tessy发现分支覆盖率只有85%，一个<code>if(pad_len<0)</code>分支不可达</li><li>分析：<code>pad_len</code>是<code>int32_t</code>，但来自被调函数返回的<code>uint32_t</code>，隐式转换后永远非负→if条件永远为假</li><li>修复：修改函数原型或增加显式范围检查</li><li>若不修复：畸形输入下可能发生数组越界</li></ul><p>其他发现的典型问题：分支不可达、资源泄漏（未释放的DMA缓冲区）、整型溢出等。</p>` },
      { id: "ri-7", tags: ["海康","Tessy","进阶"], q: "[海康] Tessy测试中分支不可达和资源泄漏你是怎么发现的？", a: `<p>Tessy通过<strong>代码插桩</strong>记录每次测试执行的路径。生成覆盖率报告后，未覆盖的分支标记为黄色/红色。分析这些分支：(1)确认测试用例是否遗漏该路径→补充用例 (2)确认分支是否真正不可达（逻辑死代码）→修复源代码。</p><p>资源泄漏检测：Tessy可跟踪<code>malloc/free</code>的配对情况。在dmaheap模块中发现某个错误返回路径释放了pool但未释放pool->chunks数组。修复方式是统一用goto cleanup模式确保所有出口都走释放逻辑。</p>` },

      // ========== 海康威视实习 - DTS ==========
      { id: "ri-8", tags: ["海康","DTS","Linux"], q: "[海康] 基于DTS完成硬件资源注册与中断配置的流程？以SPI为例", a: `<p><strong>完整流程：</strong></p><ol><li><strong>DTS节点编写</strong>：<code>reg</code>（基址+长度）、<code>interrupts</code>（<控制器类型 中断号 触发方式>，如<GIC_SPI 45 IRQ_TYPE_EDGE_RISING>）、<code>clocks</code>、<code>pinctrl-0</code></li><li><strong>驱动匹配</strong>：<code>of_match_table</code>中<code>compatible</code>字符串与DTS的<code>compatible</code>属性匹配→probe被调用</li><li><strong>资源获取</strong>：<code>platform_get_resource(pdev, IORESOURCE_MEM, 0)</code>获取寄存器基址 → <code>devm_ioremap_resource</code>映射</li><li><strong>中断注册</strong>：<code>platform_get_irq(pdev, 0)</code>→<code>devm_request_irq</code>绑定ISR（注意ISR中不能睡眠）</li></ol><p><strong>调试手段：</strong><code>cat /proc/interrupts</code>查看中断计数、<code>cat /proc/device-tree/spi@xxx/interrupts</code>验证DTS解析结果、<code>dtc -I dtb -O dts</code>反编译dtb验证。</p>` },
      { id: "ri-9", tags: ["海康","DTS","调试"], q: "[海康] DTS中断配置遇到过什么问题？如何排查？", a: `<p><strong>遇到过中断号写错导致不触发的问题。</strong>现象是驱动probe成功但ISR从未被调用。</p><p><strong>排查步骤：</strong></p><ol><li>对比芯片手册中该外设的中断线编号与DTS中<code>interrupts</code>第二个cell是否一致</li><li>查看<code>/proc/interrupts</code>看中断计数是否为0</li><li>确认引脚复用（pinctrl）配置正确</li><li>确认驱动是否成功调用<code>devm_request_irq</code>（检查返回值）</li><li>如果是共享中断，确认中断控制器支持且所有共享设备都正确处理了"不是我的中断"的情况</li></ol><p>定位后修正DTS中断号即可。另一个常见问题是<code>reg</code>地址空间与其他设备重叠，通过检查<code>reserved-memory</code>节点解决。</p>` },

      // ========== 海康威视实习 - U-Boot快启优化 ==========
      { id: "ri-10", tags: ["海康","U-Boot","OTA","高频"], q: "[海康] U-Boot快启优化你做了哪些工作？启动时间缩短了多少？", a: `<p><strong>背景：</strong>车载产品支持OTA，U-Boot是OTA升级流程的关键环节，启动速度直接影响升级窗口和回滚停机时间。</p><p><strong>瓶颈分析：</strong>用<code>get_timer()</code>埋点打印各阶段耗时→MMC初始化400ms、网络驱动300ms、USB初始化200ms、还有不必要的SD卡槽检测。</p><p><strong>三项优化：</strong></p><ul><li><strong>裁剪冗余驱动</strong>：OTA升级包在进U-Boot前已下载到eMMC，不需要网络和USB。关闭<code>CONFIG_NET</code>和<code>CONFIG_USB</code>及关联命令，镜像缩小、初始化更快</li><li><strong>减少非必要外设初始化</strong>：板上有两个MMC控制器（eMMC+SD卡），SD卡在U-Boot阶段完全不用，直接在设备树删掉SD卡节点（注意：disable不够——MMC驱动遍历所有节点仍会尝试访问寄存器；需彻底删节点）</li><li><strong>精简设备树</strong>：禁用多余的UART、I2C触摸屏、音频等节点，简化pinctrl只保留必需引脚组</li></ul><p><strong>踩坑：</strong>关掉网络后环境变量保存失败——因为MAC地址存储依赖网络子系统。换方案：直接从SoC OTP读MAC地址。</p><p><strong>最终效果：</strong>启动从<strong>1.2s降到0.7s，优化超过40%</strong>，镜像减少120KB。升级写入有更多时间校验，回滚停机时间缩短1/3。</p>` },
      { id: "ri-11", tags: ["海康","U-Boot","进阶"], q: "[海康] U-Boot优化中把SD卡节点disable后eMMC也初始化失败了，为什么？怎么解决的？", a: `<p><strong>根因：</strong>该MMC驱动在probe时会遍历设备树中所有MMC控制器节点（包括disabled的），对每个节点尝试读取寄存器来判断是否存在。SD卡节点虽然disabled但仍在设备树中，驱动仍尝试访问SD卡的MMC控制器寄存器——但SD卡槽是空的或未上电→读取寄存器返回异常→驱动误判为错误→整个MMC子系统初始化失败→eMMC也受影响。</p><p><strong>解决：</strong>不是disable节点（status="disabled"），而是直接将SD卡节点从设备树中删除。驱动遍历时就完全看不到这个节点，不会去碰它。</p><p><strong>教训：</strong>disable和删除在设备树语义上不同——disable表示"硬件存在但软件不使用"，删除表示"硬件不存在"。对于会主动遍历所有节点的驱动，需要根据实际情况选择正确的方式。</p>` },

      // ========== 经纬恒润实习 ==========
      { id: "ri-12", tags: ["经纬恒润","UDS","Bootloader","高频"], q: "[经纬恒润] 描述一下基于UDS on CAN的Bootloader刷写流程", a: `<p><strong>完整刷写流程：</strong></p><ol><li><strong>诊断会话控制(0x10 0x03)</strong>：切换到扩展会话，TesterPresent(0x3E)维持会话</li><li><strong>安全访问(0x27)</strong>：请求Seed→ECU返回随机数→上位机根据Seed+内部算法计算Key→发送Key→ECU验证通过解锁</li><li><strong>下载流程</strong>：RequestDownload(0x34)→指定起始地址和数据长度→TransferData(0x36)→按块（block）发送固件数据→RequestTransferExit(0x37)→CRC完整性校验确认</li><li><strong>ECU复位(0x11)</strong>：硬复位进入新的应用程序</li></ol><p><strong>我的职责：</strong>负责上位机（VBA脚本）与BCM之间的刷写交互逻辑，实现上述流程的自动化脚本。每条诊断请求/响应的超时处理和错误重试机制都在脚本中实现。</p>` },
      { id: "ri-13", tags: ["经纬恒润","调试"], q: "[经纬恒润] 刷写过程中遇到过VBA报文冲突的问题，怎么解决的？", a: `<p><strong>问题：</strong>通过VBA发送0x22 0x01 0x12获取版本号的报文，与Normal Communication（胎压模式、钥匙模式下对应byte递增）的0x80报文发生了冲突。两个不同来源的诊断请求在同一时刻竞争CAN总线。</p><p><strong>排查：</strong>查看源码发现两种报文的发送时机产生了重叠——Normal Comm的周期发送正碰上了VBA的诊断请求。CAN ID虽然不同但都在同一总线上，仲裁后某个会延迟，且延迟后的响应时序被打乱。</p><p><strong>解决：</strong>在VBA脚本中增加标志位检查——发送诊断请求前先检查Normal Comm是否正在进行关键通信，用特定标志位（模式切换标志）来指示当前是否允许发送诊断指令。诊断请求只在安全窗口（无Normal Comm冲突风险时）发送。</p>` },
      { id: "ri-14", tags: ["经纬恒润","Polyspace","静态分析"], q: "[经纬恒润] Polyspace静态分析发现了哪些类型的Bug？", a: `<p>对BCM应用层代码（胎压监测、钥匙匹配、LIN通信）进行Polyspace检查，发现10+处问题：</p><table><tr><th>类型</th><th>数量</th><th>示例</th></tr><tr><td>未使用变量</td><td>~3处</td><td>遗留调试变量未删除</td></tr><tr><td>数组越界风险</td><td>2处</td><td><code>uint8_t buf[8]</code>访问索引8（最大下标应为7）</td></tr><tr><td>空指针解引用</td><td>1处</td><td>函数返回NULL后未检查直接使用</td></tr><tr><td>整型转换丢失符号</td><td>2处</td><td>有符号负数隐式转为无符号大数</td></tr><tr><td>死代码</td><td>2处</td><td><code>if(0)</code>或永远为真的分支</td></tr><tr><td>非初始化变量</td><td>2处</td><td>局部变量未赋初值就使用</td></tr></table><p>Polyspace的优势在于不需要实际运行代码，通过抽象解释分析所有可能的执行路径。在汽车功能安全（ISO26262）中使用MISRA C+Polyspace是标准实践。</p>` },

      // ========== 个人项目 - 五层架构 ==========
      { id: "ri-15", tags: ["架构","五层架构","高频"], q: "[项目] 你设计的五层架构分别是什么？为什么是五层不是三层？", a: `<p><strong>五层定义：</strong></p><ol><li><strong>硬件层</strong>：STM32 HAL+CMSIS，芯片厂商寄存器操作库，不改动</li><li><strong>系统抽象层</strong>：OSAL封装RT-Thread API + HAL封装GPIO/SPI/I2C，全项目仅<strong>8个文件</strong>包含STM32寄存器操作。换芯片只改这一层</li><li><strong>驱动层</strong>：每个外设定义函数指针接口表（ops结构体），通过设备注册表按名称管理，上层不依赖具体芯片头文件</li><li><strong>服务层</strong>：纯C业务逻辑（心率算法/电量算法/罗盘/计算器），<strong>零硬件依赖</strong>，可在PC端独立编译测试</li><li><strong>应用层</strong>：线程管理+UI数据绑定，7个线程+4条消息队列，数据刷新到LVGL控件</li></ol><p><strong>为什么是五层？</strong>三层（HAL→Driver→App）是Demo级别的，驱动和业务混在一起。五层把"系统抽象"和"服务"独立出来——换芯片只动系统抽象层<strong>8个文件</strong>，服务层完全不改。架构的核心价值就是隔离变化。</p>` },
      { id: "ri-16", tags: ["架构","多态","函数指针","高频"], q: "[项目] 函数指针接口表是什么？怎么实现C语言多态？", a: `<p>每类外设定一个<code>xxx_ops_t</code>结构体，成员全是函数指针。例如IMU接口：</p><pre><code class="language-c">typedef struct {
    int32_t (*init)(void);
    bool    (*read_accel_gyro)(drv_imu_data_t *data);
    bool    (*is_data_ready)(void);
} imu_ops_t;</code></pre><p>MPU6050实现一份<code>mpu6050_imu_ops</code>，LSM303实现一份<code>lsm303_imu_ops</code>。上层代码拿到<code>imu_ops_t*</code>指针，调用<code>ops->read_accel_gyro(&data)</code>——编译器通过函数指针间接跳转到具体芯片实现，不关心背后是哪个芯片。</p><p><strong>换芯片时：</strong>只需在<code>board_init</code>中将<code>dev_register("imu", &mpu6050_imu_ops)</code>改为<code>dev_register("imu", &icm42688_imu_ops)</code>，上层<strong>50+文件零改动</strong>。这就是用函数指针表在C语言中实现多态（运行时动态绑定）。</p>` },
      { id: "ri-17", tags: ["架构","依赖倒置","SOLID","高频"], q: "[项目] 设备注册表是什么？怎么实现依赖倒置原则？", a: `<p><strong>设备注册表</strong>是一个全局数组，<code>board_init()</code>在启动时注册所有外设：</p><pre><code class="language-c">dev_register("imu", &mpu6050_imu_ops);
dev_register("display", &st7789_display_ops);</code></pre><p>服务层通过名称查找接口并调用：</p><pre><code class="language-c">imu_ops_t *imu = (imu_ops_t *)dev_get_ops("imu");
imu->read_accel_gyro(&data); // 不知道也不关心是MPU6050还是LSM303</code></pre><p><strong>依赖倒置的含义：</strong>传统写法是服务层<code>#include "mpu6050.h"</code>——上层直接依赖下层具体实现（箭头向下）。注册表反转了这个方向：服务层只依赖<code>imu_ops_t</code>抽象接口，具体实现由<code>board_init</code>注入——依赖从"上层→具体"变成了<strong>"上层→抽象←具体"</strong>。这就是SOLID原则中依赖倒置原则（DIP）在嵌入式C语言中的落地。</p>` },
      { id: "ri-18", tags: ["架构","HAL"], q: "[项目] 怎么证明硬件依赖真的被收敛到HAL层了？换芯片要改多少？", a: `<p><strong>证据：</strong>全项目搜索<code>#include "stm32f4xx_hal.h"</code>——结果仅出现在<code>hal/</code>目录下<strong>8个</strong><code>hal_*_stm32.c</code>文件中。<code>drivers/</code>、<code>services/</code>、<code>app/</code>目录<strong>零出现</strong>。</p><p><strong>换芯片（STM32→ESP32）工作量：</strong></p><ul><li>替换<code>hal/</code>下8个impl文件+1个board文件，约2-3天</li><li><code>drivers/</code>、<code>services/</code>、<code>app/</code>约<strong>50+文件零改动</strong></li><li>约<strong>80%代码直接复用</strong></li></ul><p>换RTOS：改<code>osal/</code>目录下5个<code>.c</code>文件，因为上层只用<code>os_thread_create</code>等抽象接口，约1天。换外设芯片：新增一个ops实现文件+改一行dev_register参数即可。三种变更互不干扰，可独立进行。</p>` },
      { id: "ri-19", tags: ["架构","IPC","实时性","高频"], q: "[项目] 层间为什么用直接调用而不是全用消息队列？边界怎么决定？", a: `<p><strong>核心决策：同一条线程内的调用链用直接函数调用；跨线程用消息队列。</strong></p><p><strong>原因：</strong>如果每次传感器读取都走App→MQ→Service→MQ→Driver→MQ→返回路径，一次读取需要<strong>4次上下文切换</strong>（Cortex-M4上每次约5-10μs），累积延迟对需要60fps刷新的LVGL显示完全不可接受。</p><p><strong>最终方案：</strong>App→Service→Driver→HAL全部直接函数调用（纳秒级跳转，零IPC开销）。只有跨线程场景——按键线程通知LVGL线程、定时器通知电源管理线程——才用消息队列异步通信，各线程独立运行互不阻塞。</p><p>这是PX4飞控和ESP-IDF都在用的<strong>"垂直直接调用 + 水平消息队列"</strong>模式。不是越解耦越好——解耦有代价（上下文切换），要在性能和可维护性之间找到平衡点。</p>` },
      { id: "ri-20", tags: ["架构","高内聚低耦合","高频"], q: "[项目] 你的架构怎么体现高内聚低耦合？举个具体例子", a: `<p><strong>高内聚——每个模块只做一件事：</strong></p><ul><li><code>hal_i2c_stm32.c</code>只管I2C起始/停止/发送/接收位操作，不关心上层是温湿度传感器还是EEPROM</li><li><code>svc_hr_algo.c</code>只管7点滑动窗口PPG峰值检测，内部环形缓冲区管理采样数据，不碰任何GPIO或I2C</li><li><code>drv_display_st7789.c</code>只管ST7789初始化和像素刷新，不碰LVGL任何概念</li></ul><p><strong>低耦合——模块间只通过接口通信：</strong></p><ul><li><code>svc_sensor_fusion.c</code>通过<code>dev_get_ops("imu")</code>和<code>dev_get_ops("mag")</code>获取接口，<strong>整个文件没有一行</strong><code>#include "mpu6050.h"</code></li><li>换芯片时dev_get_ops返回新芯片的ops指针，这个文件一行不用改</li><li><code>ble_thread</code>和<code>key_thread</code>通过<code>os_mq_send(key_mq)</code>通信，互不调用对方函数、互不访问对方变量——一个crash不会拖死另一个</li></ul><p>效果：改HAL不影响Service，加新传感器只需实现ops然后注册，不改已有代码。</p>` },
      { id: "ri-21", tags: ["架构","弯路","面试技巧"], q: "[项目] 你做架构设计时走过哪些弯路？怎么纠正的？", a: `<p><strong>两个弯路：</strong></p><p><strong>1. IPC边界问题：</strong>一开始想在层间全用消息队列做异步解耦。画完时序图发现一次传感器读取需要4次上下文切换，延迟太高。查阅了PX4飞控和ESP-IDF源码后确认业界标准是"垂直直接调用+水平消息队列"，改了过来。</p><p><strong>2. 设备管理过度设计：</strong>最初想引入Linux的platform bus做设备注册/匹配/probe。写完伪代码发现项目只有约10个外设且编译期全部已知，probe/match/deferred probe的代码量远超实际价值。最终用一个全局数组+名称字符串查找替代，代码从预期的<strong>300+行缩减到60行</strong>，功能完全够用。</p><p><strong>核心教训：</strong>架构不是越复杂越好，适合项目规模的才是好架构。过度设计比设计不足更消耗开发时间。</p>` },

      // ========== 个人项目 - 算法 ==========
      { id: "ri-22", tags: ["算法","心率","PPG","高频"], q: "[项目] 心率是怎么算出来的？从MAX30102原始数据到BPM的完整链路", a: `<p>MAX30102每10ms输出一个18位采样值（红光+红外两个通道PPG波形）。处理链路分四步：</p><ol><li><strong>去直流（DC Removal）</strong>：PPG波形骑在很大的DC基线上（来自皮肤/骨骼/非脉搏血液的固定衰减，幅度是脉搏波动的几十倍）。用一阶IIR低通（α=0.01，截止频率0.1Hz）跟踪极慢速基线变化，原始信号减基线得到纯脉搏波动信号</li><li><strong>带通滤波</strong>：有用频段0.5Hz~5Hz（对应30~300 BPM）。两级二阶IIR级联实现四阶带通，阻带衰减约40dB，滤掉呼吸漂移(<0.3Hz)和工频/运动伪影(>5Hz)。系数用Q15定点格式，避免Cortex-M4浮点慢</li><li><strong>自适应阈值峰检测</strong>：7点滑动窗口扫描滤波后信号，窗口中心点≥其余6个点认定为心跳峰值。阈值动态计算（每7个采样点的均值+极差的1/4），自动适配不同用户信号强弱差异</li><li><strong>后处理</strong>：两峰间隔<425ms（>141BPM为噪声）丢弃；连续收集7个有效瞬时心率值取算术平均为最终BPM</li></ol><p>与Polar H10胸带对比：静坐±2 BPM，步行±3 BPM。</p>` },
      { id: "ri-23", tags: ["算法","血氧","高频"], q: "[项目] 血氧AC/DC比值法怎么算的？", a: `<p>血氧利用含氧/脱氧血红蛋白对红光和红外光吸收率不同的特性。流程：</p><ol><li>取红光和红外两个通道各32个采样点的滑动窗口</li><li>窗口均值=DC分量（组织/骨骼/静脉血不随脉搏变化的部分）</li><li>窗口峰峰值=AC分量（动脉血随脉搏进出的波动）</li><li>R值=(红光AC/红光DC)/(红外AC/红外DC)——比值消掉了绝对幅度，只反映两个波长的相对差异</li><li>SpO2≈110-25×R（MAX30102数据手册经验校准曲线），最终钳位在70~100</li></ol><p><strong>注意：</strong>这个公式是近似公式，需要医用血氧仪做多点校准才能达到临床精度。当前实现是算法框架，精度有待标定。</p>` },
      { id: "ri-24", tags: ["算法","DSP","MATLAB"], q: "[项目] IIR滤波器参数怎么选的？MATLAB怎么验证？", a: `<ul><li><strong>去直流一阶IIR</strong>：截止频率0.1Hz，α系数取0.01（新采样值占1%，历史基线占99%），跟踪极慢，只跟体位缓慢变化走，不被脉搏波动带偏</li><li><strong>带通四阶IIR</strong>：两个二阶双二阶(Biquad)级联，低通截止5Hz滤高频噪声，高通截止0.5Hz滤呼吸漂移</li><li><strong>系数处理</strong>：系数量化为Q15定点格式（乘2^15取整），避免浮点运算在Cortex-M4上过慢。每级Biquad用6个Q15系数（b0,b1,b2,a1,a2）+2个状态变量</li></ul><p><strong>MATLAB验证流程：</strong>fdatool设计滤波器→确认通带平坦、阻带衰减≥40dB→导出系数→转为Q15定点→用实测PPG数据仿真验证→移植到C。</p>` },
      { id: "ri-25", tags: ["算法","运动识别"], q: "[项目] 运动状态识别怎么实现的？三轴加速度怎么变成运动分类？", a: `<p>基于MPU6050 DMP（内置姿态解算+六轴融合）输出四元数，不占主CPU。利用三轴加速度计算合成加速度幅值：<code>acc_mag = sqrt(ax²+ay²+az²)</code>。</p><p><strong>分类特征：</strong></p><table><tr><th>状态</th><th>加速度幅值</th><th>波动频率</th></tr><tr><td>静坐</td><td>~1g，波动<0.3g</td><td>非常低</td></tr><tr><td>步行</td><td>0.8g~1.5g</td><td>1.5~2.5Hz</td></tr><tr><td>跑步</td><td>1.2g~2.5g</td><td>2.5~3.5Hz</td></tr></table><p><strong>识别流程：</strong>4Hz低通滤波去高频→2秒滑动窗口提取峰峰幅值+过零检测频率→与经验阈值表比对→输出分类结果。DMP内部集成了姿态解算，不需CPU做复杂的卡尔曼滤波。</p>` },

      // ========== 个人项目 - 性能与功耗 ==========
      { id: "ri-26", tags: ["功耗","休眠","低功耗"], q: "[项目] 休眠电流从5mA降到0.85mA，做了哪些关键优化？", a: `<p><strong>测量工具：</strong>高精度万用表串联在电池正极测量电流。</p><p><strong>四项关键优化：</strong></p><ol><li><strong>未使用GPIO配置为模拟输入</strong>（最大项）：这一项就把电流从<strong>5mA降到2mA</strong>。GPIO默认可能是输入浮空，悬空引脚因电磁干扰产生频繁电平翻转，CMOS电路消耗大量电流</li><li><strong>关闭未使用外设时钟</strong>：TIM2/SPI2等所有未使用外设的时钟全部关闭（时钟树修剪）。每个外设即使不读写，时钟使能仍会耗电</li><li><strong>传感器进入硬件休眠</strong>：MPU6050进入sleep模式（电流仅1μA），MAX30102关闭LED驱动</li><li><strong>MCU进入STOP模式</strong>：STM32F411在Stop模式下只有RTC和唤醒中断工作，保留SRAM内容</li></ol><p><strong>待机数据：</strong>日常佩戴模式（心率+蓝牙+屏幕）约15mA，500mAh电池可用23~30h。深度休眠模式0.85mA，理论待机<strong>约24天</strong>。</p>` },
      { id: "ri-27", tags: ["GUI","LVGL","性能"], q: "[项目] GUI性能优化：87%内存节省和40%帧率提升怎么做到的？", a: `<p><strong>87%内存节省：</strong>GUI Guider生成15个screen，每个含arc/label/bar等几十个控件。页面栈最多保留当前页和上一页共2个screen（pop时调lv_obj_del释放所有子控件）。2/15≈13%，节省<strong>87%</strong>RAM。</p><p><strong>40%帧率提升（12→20fps）：</strong>不用DMA时，flush_cb里for循环逐像素SPI发送240×284全屏→CPU等约<strong>85ms</strong>。改为LVGL<strong>双缓冲+DMA</strong>后，LVGL在Buffer1渲染下一块时DMA在后台发送Buffer2，全屏降为约<strong>50ms</strong>，帧率从12fps提升到约20fps，提升约<strong>40%</strong>。</p><p>DMA是关键——把SPI传输从CPU阻塞等待变为DMA后台搬运，CPU可以并行做渲染计算。</p>` },
      { id: "ri-28", tags: ["功耗","测量"], q: "[项目] 待机时间是多少？休眠到唤醒需要多长时间？怎么测的？", a: `<p><strong>待机时间：</strong>电池500mAh。日常佩戴模式（心率+蓝牙+屏幕）约15mA，可用约1~1.5天。深度休眠（仅RTC和唤醒中断）0.85mA，理论待机约<strong>588小时（24天）</strong>。每天抬腕亮屏50次用心率监测8小时，实际约1~1.5天。</p><p><strong>唤醒时间：150~200ms（用户无感）</strong>。测量方法：GPIO翻转+示波器——在唤醒入口翻转一个引脚，在系统完全就绪（屏幕点亮、蓝牙可交互）翻转另一个引脚，波形宽度即唤醒耗时。硬件层面STM32从Stop模式唤醒仅需3.6μs，主要耗时在软件层面（SPI屏幕初始化、RT-Thread任务恢复、蓝牙重连）。</p>` },
      { id: "ri-29", tags: ["通信","串口","性能"], q: "[项目] KT6368串口吞吐量是多少？协议开销占多少？", a: `<p>配置波特率115200bps，1个起始位+8数据位+1停止位=10bit/byte→理论最大吞吐量约<strong>11.5 KB/s</strong>。</p><p>实际场景：心率数据每包4字节，OTA固件256字节分片。考虑协议开销（包头2字节+校验1字节+应答帧），实测有效吞吐量约<strong>8~9 KB/s</strong>，协议效率约70%~78%。如果数据更碎片化（小包多），效率会更低——因为每包都有固定开销。优化方向：批量打包发送，减少握手次数。</p>` },

      // ========== 技术深度问答 ==========
      { id: "ri-30", tags: ["RT-Thread","任务切换","进阶"], q: "RT-Thread中任务切换的完整流程是怎样的？从SysTick到PendSV讲一下", a: `<p><strong>完整链路：</strong>SysTick中断→<code>rt_os_tick_callback</code>→更新全局tick→递减当前线程剩余时间片。若时间片归零→<code>rt_thread_yield()</code>→<code>rt_schedule()</code>选最高优先级就绪线程→<code>rt_hw_context_switch()</code>悬起PendSV。SysTick退出后，PendSV_Handler执行真正上下文切换：保存当前线程R4-R11→恢复下一个线程寄存器→完成切换。</p><p><strong>软定时器触发高优先级任务抢占的情况：</strong><code>rt_timer_check()</code>在同一个SysTick_Handler中执行超时回调（如<code>rt_sem_release</code>唤醒高优先级线程）。该线程进入就绪态后，即使当前线程时间片未用完，调度器通过全局优先级位图检测到更高优先级就绪线程→<code>rt_schedule()</code>主动触发PendSV→立即抢占。</p><p><strong>关键设计：</strong>利用Cortex-M的PendSV（优先级最低）实现上下文切换——确保在所有ISR处理完毕后才做切换，不打断正在执行的ISR。</p>` },
      { id: "ri-31", tags: ["RT-Thread","FreeRTOS","对比"], q: "RT-Thread相比FreeRTOS多了哪些组件？", a: `<ul><li><strong>设备框架(rt_device)</strong>：统一设备操作接口（rt_device_find/read/write），方便驱动复用，类似Linux设备模型</li><li><strong>Finsh Shell控制台</strong>：交互式命令行，支持查看线程/内存/设备、执行函数，嵌入式调试利器</li><li><strong>虚拟文件系统(DFS)</strong>：支持FAT/LittleFS/NFS等，统一VFS接口</li><li><strong>SAL套接字抽象层</strong>：屏蔽底层网络协议栈差异（lwIP/AT Socket），应用层无感知切换</li><li><strong>软件包生态</strong>：400+第三方package可通过menuconfig一键集成（LVGL/AT指令/MQTT/HTTP等）</li><li><strong>传感器框架</strong>：已支持100+传感器驱动</li></ul><p>FreeRTOS只提供核心调度+IPC，其余需自行集成。RT-Thread是一个完整的IoT OS平台。</p>` },
      { id: "ri-32", tags: ["Linux","驱动","对比"], q: "Linux驱动开发和STM32裸机/RTOS驱动开发最大的区别是什么？", a: `<p><strong>三大核心区别：</strong></p><ol><li><strong>架构不同</strong>：Linux有统一的设备模型（platform_device/driver），驱动必须遵循框架规范（probe/remove/fops）；STM32驱动自由度高，直接操作寄存器即可</li><li><strong>内存管理不同</strong>：Linux有虚拟内存，驱动运行在内核态，不能直接访问物理地址，必须先ioremap成虚拟地址；STM32是物理内存，直接访问寄存器地址</li><li><strong>并发控制不同</strong>：Linux是多用户多任务系统，驱动需考虑多进程同时访问（用spinlock/mutex保护）；RTOS虽有多任务但没有进程概念，共享内存空间中并发控制相对简单</li></ol><p>Linux驱动开发门槛更高——需要理解内核框架、设备模型、并发保护、内核内存管理等。但一旦掌握了框架，写驱动是有章可循的；STM32驱动更自由但也更容易写出不规范代码。</p>` },
      { id: "ri-33", tags: ["Bootloader","跳转"], q: "Bootloader中跳转到应用程序的具体步骤是什么？", a: `<pre><code class="language-c">#define APP_ADDR 0x08008000

void jump_to_app(void) {
    // 1. 检查APP是否存在（读EEPROM标志或APP起始地址内容）
    if (*(uint32_t*)APP_ADDR == 0xFFFFFFFF) return; // APP不存在

    // 2. 关闭SysTick和全局中断
    SysTick->CTRL = 0;
    __disable_irq();

    // 3. 重定向向量表
    SCB->VTOR = APP_ADDR;

    // 4. 设置MSP为APP的栈顶地址
    __set_MSP(*(uint32_t*)APP_ADDR);

    // 5. 获取APP复位向量并跳转
    void (*app_reset_handler)(void) = (void (*)(void))*(uint32_t*)(APP_ADDR + 4);
    app_reset_handler();  // 永不返回
}</code></pre><p><strong>关键点：</strong>关SysTick（防止跳转过程中产生中断）、关全局中断、设置VTOR（APP使用自己的向量表）、设置MSP（APP的栈指针从APP固件头读出）、函数指针跳转。</p>` },
      { id: "ri-34", tags: ["设备树","Linux"], q: "设备树在哪一步加载？作用是什么？为什么需要设备树？", a: `<p><strong>加载时机：</strong>设备树（DTB）由U-Boot加载（从eMMC/SD/NAND读到内存指定地址）→启动内核时通过寄存器R2传递DTB地址→内核在<code>start_kernel</code>之前的<code>setup_machine_fdt</code>中解析设备树，建立设备模型。</p><p><strong>作用：</strong>以结构化方式描述板级硬件信息（寄存器地址、中断号、时钟、GPIO、总线拓扑）。</p><p><strong>为什么需要：</strong>在设备树之前，ARM平台每个板子要写board-xxx.c板级文件，硬件变一点就要改内核代码重新编译。引入设备树后：(1)硬件信息与内核代码解耦 (2)同一个zImage+不同dtb适配多个硬件平台 (3)驱动不再写死地址/中断号 (4)改硬件只需改dts，无需重新编译内核。</p>` },
      { id: "ri-35", tags: ["Linux","IPC"], q: "Linux进程间通信(IPC)方式及使用场景？", a: `<table><tr><th>方式</th><th>特点</th><th>使用场景</th></tr><tr><td>匿名管道</td><td>半双工、仅父子进程</td><td>popen()读取命令输出</td></tr><tr><td>有名管道(FIFO)</td><td>无亲缘进程可通信</td><td>模拟传感器数据源</td></tr><tr><td>消息队列</td><td>消息边界清晰、有序传递</td><td>小块结构化数据传递</td></tr><tr><td>共享内存</td><td>最快速（零拷贝）</td><td>视频帧传递（配合信号量同步）</td></tr><tr><td>信号</td><td>异步通知、信息量少</td><td>SIGIO异步I/O事件</td></tr><tr><td>Socket</td><td>跨网络/本地通信</td><td>本机进程间(Unix domain)或网络</td></tr></table>` },
      { id: "ri-36", tags: ["协议","SPI","I2C","对比"], q: "SPI和I2C在总线协议上的区别？什么场景选哪个？", a: `<table><tr><th>特性</th><th>SPI</th><th>I2C</th></tr><tr><td>信号线</td><td>4根(MOSI/MISO/SCLK/CS)</td><td>2根(SDA/SCL)</td></tr><tr><td>时钟与应答</td><td>主机产生时钟，无应答</td><td>主机产生时钟，每字节后有ACK/NACK</td></tr><tr><td>多主仲裁</td><td>不支持，通过CS区分从机</td><td>支持，通过SDA线与仲裁（低电平优先）</td></tr><tr><td>速率</td><td>可达几十MHz</td><td>100k/400k/1MHz</td></tr><tr><td>全/半双工</td><td>全双工</td><td>半双工</td></tr></table><p><strong>选型经验（项目实践）：</strong>心率传感器EM7028用I2C（引脚少、400kbps足够），LCD屏幕用SPI（需要高刷新率、MHz级传输）。规则：高速大量数据→SPI；引脚紧张→I2C。</p>` },
      { id: "ri-37", tags: ["调试","面试技巧"], q: "全局变量的值与预期不一样，怎么排查？", a: `<ol><li><strong>定位所有写入点</strong>：查看源码中哪些位置修改该变量，检查是否有不该写的地方在写</li><li><strong>检查越界覆盖</strong>：在变量前后放置哨兵字节（Magic Number），若哨兵被修改说明是越界覆盖</li><li><strong>数据断点（Watchpoint）</strong>：调试器中设硬件断点，该地址被写入时自动中断，查看调用栈——最快的方法</li><li><strong>并发修改</strong>：若被中断和主循环同时访问，临时加临界区验证是否竞态条件引起</li><li><strong>volatile检查</strong>：若变量在中断中修改，确认声明为volatile，否则编译器可能用寄存器缓存旧值</li><li><strong>编译器优化</strong>：降低优化级别（-O0），看问题是否消失，确认是否与优化相关</li></ol>` },
      { id: "ri-38", tags: ["C语言","内存对齐"], q: "怎么防止结构体内存对齐？什么时候需要紧凑排列？", a: `<p><strong>方法：</strong>用<code>#pragma pack(1)</code>或<code>__attribute__((packed))</code>。</p><pre><code class="language-c">struct __attribute__((packed)) packed_struct {
    char a;    // 1 byte
    int b;     // 4 bytes（本来有3 byte padding）
    short c;   // 2 bytes
}; // 总大小7字节而不是12字节</code></pre><p><strong>需要紧凑排列的场景：</strong></p><ul><li>通信协议帧解析（帧格式按字节紧密排列，padding会破坏解析）</li><li>硬件寄存器映射（寄存器布局由硬件固定）</li><li>Flash/EEPROM中存储结构体（节省空间+读写一致性）</li></ul><p><strong>代价：</strong>非对齐访问在某些架构上可能触发HardFault（Cortex-M0），或效率降低（需要多次字节组合）。只在必要时使用。</p>` },
      { id: "ri-39", tags: ["RTOS","实时性"], q: "线程时间片设为5ms，实时性高吗？", a: `<p>5ms时间片不算高实时，属于<strong>常规配置</strong>。RT-Thread是<strong>抢占式内核</strong>，高优先级任务可以<strong>立即抢占</strong>低优先级任务——实时性由调度机制（抢占+优先级）决定，不是由时间片决定。时间片只影响同优先级任务间的轮转频率。</p><p>5ms可满足一般嵌入式场景（如穿戴设备的心率检测/UI刷新）。工业/汽车级高实时场景（如电机FOC控制/ABS制动）需要：</p><ul><li>更短时间片（1ms或更小）</li><li>更高的tick频率（如10kHz）</li><li>甚至不用tick调度而用硬件定时器直接触发最高优先级任务</li></ul>` },

      // ========== 开放性问题 ==========
      { id: "ri-40", tags: ["HR","面试技巧"], q: "[面试官常问] 如何看待AI？日常会使用AI工具吗？", a: `<p>我认为AI（特别是大语言模型）已经成为软件开发中<strong>非常高效的辅助工具</strong>。它不能替代工程师对系统底层原理的理解和调试能力，但可以极大提升学习和生产效率。</p><p><strong>我的实际使用方式：</strong></p><ol><li><strong>快速理解新协议/芯片手册</strong>：看EM7028传感器手册时，让AI帮忙总结寄存器配置流程，然后我再对照手册仔细验证——相当于一个能快速定位关键信息的"智能助手"</li><li><strong>代码Review辅助</strong>：把核心代码片段让AI检查潜在边界问题，但不盲从——AI给的建议我会逐条分析合理性</li><li><strong>面试准备</strong>：让AI基于我的项目模拟面试官追问，发现回答中的薄弱点</li></ol><p><strong>底线：</strong>所有AI输出都要经过自己的理解验证。不理解原理的代码绝对不能直接使用。AI是工具，人做决策。</p>` },
      { id: "ri-41", tags: ["项目","难点","面试技巧","高频"], q: "[面试官常问] 你这个项目最大的技术难点是什么？怎么解决的？", a: `<p><strong>最大的难点不是某个具体Bug，而是架构决策。</strong></p><p><strong>决策一：IPC边界问题。</strong>一开始想在层间全用消息队列做异步解耦，画完时序图发现一次传感器读取需要4次上下文切换，延迟高到不可接受。查阅PX4飞控和ESP-IDF源码后确认业界标准是"垂直直接调用+水平消息队列"，纠正了设计。</p><p><strong>决策二：设备管理过度设计。</strong>最初想引入Linux platform bus做设备注册/匹配/probe，写完伪代码后发现项目只有10个外设且编译期全部已知，probe/match的代码量远超实际价值。最终用全局数组+名称查找替代，代码从300+行缩减到60行。</p><p><strong>核心收获：</strong>架构不是越复杂越好，适合项目规模的才是好架构。这两个决策让我在"解耦"和"简单"之间找到了平衡点。</p>` },
      { id: "ri-42", tags: ["RTOS","调试"], q: "[项目] 高优先级任务占着CPU导致低优先级任务饿死，你怎么解决？", a: `<p><strong>遇到过。</strong>项目初期心率算法任务优先级设为3（较高），计算耗时约50ms，导致GUI更新任务（优先级6）长时间得不到运行，界面卡顿。</p><p><strong>解决方案：</strong></p><ol><li><strong>让出CPU</strong>：心率任务在完成一次计算后主动<code>rt_thread_delay(10)</code>挂起10ms，给GUI任务执行窗口——这是最简单的方案</li><li><strong>降低计算频率</strong>：分析发现没必要每次心跳都更新显示，改为每5次计算刷新一次GUI</li><li><strong>计算分段</strong>：把50ms的算法拆成多个小段，每段执行完主动yield，避免长时间霸占CPU</li></ol><p>根本原则：高优先级任务不能长时间占用CPU。必须给低优先级任务留出执行窗口（通过delay/yield或提高tick频率）。</p>` },
      { id: "ri-43", tags: ["调试","FIFO","传感器"], q: "[项目] EM7028心率传感器数据突然归零的问题怎么排查和解决的？", a: `<p><strong>现象：</strong>设备运行几分钟后心率数据突然归零，重启后恢复。</p><p><strong>排查过程：</strong></p><ol><li>示波器抓I2C总线波形→确认数据传输仍在进行，传感器没死</li><li>读数据手册→发现传感器默认采样率<strong>100Hz</strong>，内部FIFO大小有限（32 samples）</li><li>分析代码→读取周期设的是<strong>100ms（10Hz）</strong>——远低于传感器输出速率（100Hz）</li><li>RT-Thread任务调度导致实际读取间隔不稳定→传感器每秒产生100个样本但代码每秒只取10个→FIFO在约0.3秒内溢出→后续数据全部丢失→归零</li></ol><p><strong>解决：</strong>配置传感器采样率降到10Hz匹配读取周期、增加连续读失败3次则软复位传感器的恢复逻辑。此后数据稳定。</p>` },
      { id: "ri-44", tags: ["OTA","AB分区"], q: "[追问] 汽车OTA升级AB分区机制如何保证安全？", a: `<p>AB分区机制：Flash分为A区（当前运行固件）和B区（升级目标固件）。</p><p><strong>安全保障机制：</strong></p><ol><li><strong>写入阶段</strong>：固件分块写入B区，每块<strong>CRC32校验</strong>→全部写入后验证<strong>ECDSA数字签名</strong>→防传输错误和固件篡改</li><li><strong>切换阶段</strong>：设置升级标志位→重启→Bootloader检测标志→验证B区固件完整性（<strong>SHA256+签名</strong>）→验证通过才切换活动分区</li><li><strong>回滚机制</strong>：B区启动后执行健康检查（心跳正常+通信OK+功能自测）→通过则<strong>提交</strong>固件（commit→A区成为下次升级备区）→失败则**自动回滚A区**</li></ol><p><strong>防变砖的核心：</strong>Bootloader独立不可升级。无论固件怎么坏，Bootloader始终完好，能读取AB分区标志并选择正确（或上一个完好）的固件启动。</p>` },
      { id: "ri-45", tags: ["运动补偿","算法","进阶"], q: "[追问] PPG心率算法如果有运动干扰怎么办？", a: `<p><strong>当前版本没有做运动补偿，这是算法的一个局限。</strong></p><p><strong>运动伪影来源：</strong>手腕晃动→传感器和皮肤距离变化→DC基线漂移；肌肉收缩→血液灌注变化→AC信号被调制。</p><p><strong>改进方向（两个方案）：</strong></p><ol><li><strong>自适应噪声门控</strong>：利用MPU6050三轴加速度合成值——超过阈值说明用户在运动→标记这段PPG数据为不可靠→不参与心率计算。简单有效但会丢失运动期间的心率数据</li><li><strong>LMS自适应滤波</strong>：把加速度信号作为噪声参考输入→自适应滤波器从PPG信号中减去运动相关分量。能恢复运动期间的心率，但算法复杂度高、需要调参</li></ol><p>这两个方案的核心思路文献中都有（TROIKA、JOSS等），但当前项目版本还没实现。如果在面试中被追问到这个，坦诚说明局限+提出改进方向比假装完美更有说服力。</p>` },
      { id: "ri-46", tags: ["CI","自动化测试"], q: "[追问] 测试用例集成到CI流程中，是怎么实现的？", a: `<p><strong>流程：</strong>开发者提交代码→CI Jenkins Pipeline触发→自动编译→烧录目标板→运行STL测试套件→采集结果→生成报告。</p><p>STL的GTC测试用例作为测试套件的一部分，每次代码变更后自动在目标硬件上运行。如果GTC测出时间偏差超限→测试失败→CI发邮件通知提交者→代码需修复后才能合入。</p><p>此外，Tessy单元测试也在CI中有独立Pipeline，运行在PC模拟环境（不依赖硬件），检查代码覆盖率是否达标（>85%）。这种<strong>软硬结合的双层测试</strong>同时保证了代码逻辑正确性和硬件行为正确性。</p>` }
    ]
  }
];

// EMBEDDED_DATA 定义已移至 data_supplement.js 末尾
